### ISSUE TITLE
python client pre-registered in jumpscale

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#126]

**Comment by robvanmieghem** [comment]
Pull request in jumpscale core:
https://github.com/Jumpscale/jumpscale_core8/pull/316/files

**Comment by robvanmieghem** [comment]
Readme:
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/clients/itsyouonline/readme.md

**Comment by robvanmieghem** [comment]
Added to the technical introduction as well
