### ISSUE TITLE
create a nicer UI

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#128]

**Comment by robvanmieghem** [comment]
[ITSYOU.ONLINE(1).pdf](https://github.com/itsyouonline/identityserver/files/458637/ITSYOU.ONLINE.1.pdf)

**Comment by robvanmieghem** [comment]
[CENTRILOGIC_PRES.pdf](https://github.com/itsyouonline/identityserver/files/458644/CENTRILOGIC_PRES.pdf)
