### ISSUE TITLE
No access to profile after successfully creating a new user

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#149]
I created a new user on itsyou.online, can login, but cannot access my profil

When clicking Home nothing happens:

![screen shot 2016-06-13 at 17 29 29](https://cloud.githubusercontent.com/assets/13795109/16013088/670e6f2a-318c-11e6-890f-984725a32a50.png)

This only happens on Safari

**Comment by robvanmieghem** [comment]
Commit a88702444baa45c8132f42d4bd09365565201bf6 broke the rendering in Safari

**Comment by robvanmieghem** [comment]
Fixed by https://github.com/itsyouonline/identityserver/commit/ebadf54166be00397ec894f22a420a4d7ff93db1
