### ISSUE TITLE
Unable to login when using Safari

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#151]
This used to work previously

When trying to login with Safari nothing happens when clicking Login:

<img width="1127" alt="screen shot 2016-06-14 at 11 02 46" src="https://cloud.githubusercontent.com/assets/13795109/16037223/e2b24df2-321f-11e6-9702-a8b272a6aa2a.png">

**Comment by robvanmieghem** [comment]
Fixed by restarting mongo, issue for hanging mongo connections:
https://github.com/itsyouonline/identityserver/issues/152
