### ISSUE TITLE
Connections to mongo freeze sometimes on production

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#152]

**Comment by lucasvanhalst** [comment]
Every time you reload a page, 4 or more new connections to the db are opened.

**Comment by robvanmieghem** [comment]
Is also noticed on the new production system so it is probably not a lack of resources.

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/875ae78f1a1c3e9ae220aa1b9e615cbaac8f23c8
