### ISSUE TITLE
User got created while the registration failed => username taken

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#153]
It first tried to register a new user "yahoo", which failed because the sms was not send

When trying to create the user again, I got the message that the username was already taken, see below

I would expect that users are not created if the whole registration process is not completed successfully

<img width="1044" alt="screen shot 2016-06-14 at 11 53 38" src="https://cloud.githubusercontent.com/assets/13795109/16038714/a87d2d12-3226-11e6-8358-0aa0275afb20.png">

**Comment by lucasvanhalst** [comment]
@91b5eee50d066a0ab9211b3393918dd6932d8d65
