### ISSUE TITLE
Unexpected error when clicking the URL in the phone verification sms

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#154]
See below, code was accepted however

![wp_ss_20160614_0001](https://cloud.githubusercontent.com/assets/13795109/16039000/daa7a4b0-3227-11e6-9835-2825054d3288.jpeg)

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/17cf02250cad10e85f59c9fdfb833dd977a73a40
