### ISSUE TITLE
/login/twofamethods writes the headers multiple times

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#166]
```
2016-06-15T11:41:43.497681279Z 2016/06/15 11:41:43 http: multiple response.WriteHeader calls 
2016-06-15T11:41:43.497916199Z 173.245.53.193 - - [15/Jun/2016:11:41:43 +0000] "GET /login/twofamethods HTTP/1.1" 200 45
```

**Comment by grimpy** [comment]
Please add some more logs @robvanmieghem

**Comment by robvanmieghem** [comment]
2016-06-16T15:54:16.335459554Z 173.245.53.193 - - [16/Jun/2016:15:54:16 +0000] "GET /login HTTP/1.1" 200 2287 
[identityserver-1]2016-06-16T15:54:16.853246160Z 173.245.53.193 - - [16/Jun/2016:15:54:16 +0000] "GET /components/shared/directives/header.html HTTP/1.1" 304 0 
[identityserver-1]2016-06-16T15:54:16.855112132Z 173.245.53.193 - - [16/Jun/2016:15:54:16 +0000] "GET /components/login/views/twoFactorAuthentication.html HTTP/1.1" 304 0 
[identityserver-1]2016-06-16T15:54:16.863662902Z 173.245.53.193 - - [16/Jun/2016:15:54:16 +0000] "GET /components/shared/directives/footer.html HTTP/1.1" 304 0 
[identityserver-1]2016-06-16T15:54:17.058929419Z 2016/06/16 15:54:17 http: multiple response.WriteHeader calls 
[identityserver-1]2016-06-16T15:54:17.059195470Z 173.245.53.193 - - [16/Jun/2016:15:54:17 +0000] "GET /login/twofamethods HTTP/1.1" 200 23
