### ISSUE TITLE
When there is a pending invitation, this should be approvable from the "Authorize" screen.

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#184]
Use case:
An organization invites a user to a group, the user logs in to the app using itsyouonline but is unable to since the "user:memberof:group" scope is requested but not available. It would be better to accept the invitation directly from the authorize screen when the "user:memberof:group" scope is requested.

**Comment by lucasvanhalst** [comment]
https://github.com/itsyouonline/identityserver/commit/7547e056fdadf452e484ea4bc467a8df0e2a3c18
