### ISSUE TITLE
Add labelled virtual currency addresses as shareable properties.

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#185]
A virtual currency consists of an label, address, expiry datetime and a currencysymbol.

**Comment by lucasvanhalst** [comment]
suggesting we use a `virtualcurrencies` property on the user object for this

**Comment by robvanmieghem** [comment]
Can we rename it all to "digital assets" ?

**Comment by lucasvanhalst** [comment]
That sounds confusing to me

**Comment by robvanmieghem** [comment]
"digital wallets" ?
