### ISSUE TITLE
Expiration time is not send in the oauth token response.

### ISSUE THREAD

**Issue by zaibon** [itsyouonline/identityserver#193]
According to the doc an aouth token response should looks like:
```
{"access_token":"ACCESS_TOKEN","token_type":"bearer","expires_in":2592000,"refresh_token":"REFRESH_TOKEN","scope":"read","info":{"username":"bob"}}
```

Currently the `expires_in` is not present.

**Comment by robvanmieghem** [comment]
Indeed, this is missing. Would be better if it is changed to `expires_at` as well.

**Comment by lucasvanhalst** [comment]
I would leave it expires_in as that's what the spec states it should be https://tools.ietf.org/html/rfc6749#section-4.2.2

**Comment by robvanmieghem** [comment]
@lucasvanhalst Good catch!
