### ISSUE TITLE
UI Session Timeout Error

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#197]
UI Session Timeout Error not show proper error message

steps:
Sign-in in itsyou.online, then wait until session timeout, try to click on any action you will see the attached screen shot

![ef619102-395e-11e6-991c-87b67848a415](https://cloud.githubusercontent.com/assets/16098294/16361367/f3e1977e-3b96-11e6-9665-6827aa141a73.png)

**Comment by lucasvanhalst** [comment]
Should be fixed by @51e6f81dd1f6cb072635a61e67d1ca53852f15c4
