### ISSUE TITLE
An http 500 is returned instead of a 404

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#2]
When requesting an unexisting asset (`/assets/...`), an internal server error status is returned instead of a not found status code.

**Comment by mohabusama** [comment]
https://github.com/elazarl/go-bindata-assetfs/pull/26
https://github.com/jteeuwen/go-bindata/issues/114

**Comment by robvanmieghem** [comment]
I suggest removing the go-bindata-assetfs dependency and serving it ourselves.
