### ISSUE TITLE
Reset password failed to save new password

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#211]
Follow reset password link and enter new password failed with:
"The password reset token was already used or was not found."

see attachment
![screenshot from 2016-07-03 11-28-29](https://cloud.githubusercontent.com/assets/16098294/16544751/eaac5fe4-4119-11e6-8ba5-f64b81c3f309.png)

**Comment by lzonneke** [comment]
this is checked and resolved

**Comment by lzonneke** [comment]
verified on 7f2eafc
