### ISSUE TITLE
api: get authorizations for a specific user return null

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#212]
use this url: https://itsyou.online/api/users/alim/authorizations
return: null
should return the list of authorizations
see attached screen shot
![screenshot from 2016-07-03 13-56-59](https://cloud.githubusercontent.com/assets/16098294/16555581/1e27ead6-41de-11e6-8fbe-a2dfc7ef9e20.png)

**Comment by lucasvanhalst** [comment]
Do you actually have any authorizations (see the tab 'authorizations' in the UI)? The UI also uses this API so it should work

**Comment by alimcodescalers** [comment]
No, I don't have but I think it should return empty list not null, right?

**Comment by robvanmieghem** [comment]
@alimcodescalers can you add the log of the request (want to see if there is a valid sessioncookie)

**Comment by alimcodescalers** [comment]
@robvanmieghem 
Headers:
''
HTTP/2.0 200 OK
Date: Mon, 11 Jul 2016 10:49:42 GMT
Content-Type: application/json
Content-Length: 5
Server: cloudflare-nginx
cf-ray: 2c0bb0b61af74173-CAI
X-Firefox-Spdy: h2

GET /api/users/alim/authorizations HTTP/1.1
Host: itsyou.online
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://github.com/itsyouonline/identityserver/issues/212
Cookie: __cfduid=d42094cfb56cd148dc791ce07d75144dd1467109767; itsyou.online.user=alim; authenticatedsession=MTQ2ODIzNDAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQUp2LUNBQUVHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dHQUFSaGJHbHR84B9ZXpbokbVbcY-VP5h5sd5usqlAdweKuX2KgeOFew4=; loginsession=MTQ2ODIzNDAwOHxEdi1CQkFFQ180SUFBUkFCRUFBQUp2LUNBQUVHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dHQUFSaGJHbHR8gijCBge7NNMz_TGAJHJv5euq9iHpXmpeALwpFygABDM=
Connection: keep-alive
''
Response:
''
null
''

**Comment by lzonneke** [comment]
still valid on 7f2eafc

**Comment by LeeSmet** [comment]
@alimcodescalers is this still valid (on staging)?
