### ISSUE TITLE
400  when creating New API Key and not specifying label

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#214]
Should be a specific error message, not just 400 page 

![screen shot 2016-07-04 at 12 26 43](https://cloud.githubusercontent.com/assets/13795109/16557896/b0f3e280-41e2-11e6-8290-84ffa3c68145.png)

![screen shot 2016-07-04 at 12 24 56](https://cloud.githubusercontent.com/assets/13795109/16557930/d524ac20-41e2-11e6-96e1-7f2425c80aee.png)

**Comment by lucasvanhalst** [comment]
This is already fixed on the beta branch
