### ISSUE TITLE
api: dns has no requests

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#215]
api path: /organizations/{globalid}/dns 
has no requests on the documentations 

see screen shot
![screenshot from 2016-07-04 15-57-38](https://cloud.githubusercontent.com/assets/16098294/16563015/76ca5172-4208-11e6-85be-2c2814a50115.png)

**Comment by lzonneke** [comment]
still valid on 7f2eafc

**Comment by lucasvanhalst** [comment]
API clients will need to be regenerated for this

**Comment by robvanmieghem** [comment]
Removed the verifcation label since, as you mentioned, the clients sill need to be regenerated.
