### ISSUE TITLE
Can't access itsyou.online from Egypt

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#217]
Can't access itsyou.online from Egypt

see attached screen shot
![screenshot from 2016-07-12 15-22-58](https://cloud.githubusercontent.com/assets/16098294/16768421/0057a68e-484d-11e6-9d68-d821f0c17e30.png)

**Comment by robvanmieghem** [comment]
This is weird since it does work for https://staging.itsyou.online

**Comment by robvanmieghem** [comment]
Probably bgp issue where it is was deployed, moved to a different server and problems seem to be gone.
