### ISSUE TITLE
api: return null or None is not acceptable for any get reponse

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#218]
example: digitalwallet in GET /users/{username} is None 
`
13-07-2016 15:13:06 EET [ITSYOU-001] [INFO] GetUser [alim] response [{u'username': u'alim', u'phonenumbers': [{u'phonenumber': u'+201002881102', u'label': u'Personal'}], u'github': {u'login': u'alimcodescalers', u'avatar_url': u'https://avatars.githubusercontent.com/u/16098294?v=3', u'id': 16098294, u'name': u'Mahmoud Ali', u'html_url': u'https://github.com/alimcodescalers'}, u'addresses': [{u'city': u'Cairo', u'street': u'Elnozha', u'country': u'Egypt', u'label': u'Work', u'other': u'', u'postalcode': u'11331', u'nr': u'72'}], u'firstname': u'Mahmoud', u'lastname': u'Ali', u'digitalwallet': None, u'publicKeys': [], u'expire': u'0001-01-01T00:00:00Z', u'facebook': {u'picture': u'https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/10428711_436473003187588_5533426622994054745_n.jpg?oh=e42a226b8248c5ac0022d81f8e272e08&oe=57F9F61E', u'link': u'https://www.facebook.com/app_scoped_user_id/609807605854126/', u'id': u'609807605854126', u'name': u'Mahmoud Ali'}, u'emailaddresses': [{u'emailaddress': u'alim@codescalers.com', u'label': u'main'}, {u'emailaddress': u'alim@greenitglobe.com', u'label': u'work'}], u'bankaccounts': [{u'country': u'Egypt', u'iban': u'1111', u'bic': u'12345678', u'label': u'HSBC'}]}]
`
should be string/list/dict

**Comment by alimcodescalers** [comment]
GET /users/{username}/authorizations return None
`
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/users/alim/authorizations HTTP/1.1" 200 5
itsyouonline_testsuite: INFO: GetAllAuthorizations [alim] response [None]
`

**Comment by alimcodescalers** [comment]
GET /users/{username}/info for user alim get None in parameters [organizations, phonenumbers, addresses, publicKeys, emailaddresses]
`
13-07-2016 14:52:29 EET [ITSYOU-010] [INFO] GetUserInformation [alim] response [{u'username': u'alim', u'organizations': None, u'phonenumbers': None, u'github': {u'login': u'', u'avatar_url': u'', u'id': 0, u'name': u'', u'html_url': u''}, u'addresses': None, u'firstname': u'', u'lastname': u'', u'publicKeys': None, u'facebook': {u'picture': u'', u'link': u'', u'id': u'', u'name': u''}, u'emailaddresses': None}]
`

**Comment by lzonneke** [comment]
still valid on 7f2eafc
