### ISSUE TITLE
api: create new organization using python client fail with code 404

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#228]
`
requests.packages.urllib3.connectionpool: DEBUG: "POST /v1/oauth/access_token?client_secret=dZwkaFmPzyYAbdJaamO8bOtDnrDs&grant_type=client_credentials&client_id=3-RR68hSplZUWRoWN-lov9IKx4nU HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: DEBUG: "POST /api//organizations HTTP/1.1" 301 0
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/organizations HTTP/1.1" 404 19
`

**Comment by lzonneke** [comment]
still on 7f2eafc

**Comment by lucasvanhalst** [comment]
Works on on 0.9.9
