### ISSUE TITLE
Sine qua non: required optional query parameter

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#238]
See screenshot:

![screen shot 2016-08-08 at 15 08 47](https://cloud.githubusercontent.com/assets/13795109/17480828/1fbe3334-5d7a-11e6-945c-a73e148f046f.png)

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/8c3bb555395c69d362e2c5de2e4fb16c1c396e11
