### ISSUE TITLE
missing OPTIONS verb on https://itsyou.online/v1/oauth/access_token

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#243]
This request is being issued by the api console, no idea if this is the cause of the requests failing

**Comment by iwanbk** [comment]
maybe caused by bug in go-raml, go-raml doesn't generate `OPTIONS` handler

**Comment by robvanmieghem** [comment]
Not really since that endpoint was not created by go-raml. I'm looking into the api-console since it also does not seem to pass clientid and secret when you select client credentials oauth2...

**Comment by robvanmieghem** [comment]
2d42b9b77a74621ceca4ade3b88cbff09743f1f7
