### ISSUE TITLE
gui: some apis have short description 

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#245]
On page https://itsyou.online/apidocumentation check attached screen shot that indicates apis like: 
/organizations/{globalid}/apikeys
/organizations/{globalid}/dns

have short description not like the rest, those description should be removed.

![screenshot from 2016-08-16 16-03-00](https://cloud.githubusercontent.com/assets/16098294/17701756/bdcd727e-63d3-11e6-973f-79f67761926d.png)

**Comment by lzonneke** [comment]
on version 7f2eafc
