### ISSUE TITLE
api: GetUser vs GetUserInformation

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#246]
GetUserInformation not returning the expected info, check below:
`
In [102]: res=client.api.GetUser(user)

In [103]: res.json()
Out[103]: 
{u'addresses': [{u'city': u'Cairo',
   u'country': u'Egypt',
   u'label': u'Home',
   u'nr': u'14',
   u'other': u'14A',
   u'postalcode': u'11331',
   u'street': u'Elkwsny St.'}],
 u'bankaccounts': [{u'bic': u'12345678',
   u'country': u'Egypt',
   u'iban': u'987654321',
   u'label': u'HSBC'}],
 u'digitalwallet': [{u'address': u'72 Elnozha',
   u'currencysymbol': u'PS',
   u'expire': u'2017-12-31T22:00:00Z',
   u'label': u'Personal'}],
 u'emailaddresses': [{u'emailaddress': u'm_flip_flop@hotmail.com',
   u'label': u'main'}],
 u'expire': u'0001-01-01T00:00:00Z',
 u'facebook': {u'id': u'10155148869195031',
  u'link': u'https://www.facebook.com/app_scoped_user_id/10155148869195031/',
  u'name': u'\u05dd\u05d1\u05dd\u05e4\u05d1 \u05dd\u05d1\u05dd\u05d1',
  u'picture': u'https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/13770530_10155062088915031_7059947395107659110_n.jpg?oh=06aec34e1e48c0cfb129b77f8076c0e0&oe=584F80E0'},
 u'firstname': u'Mahmoud',
 u'github': {u'avatar_url': u'https://avatars.githubusercontent.com/u/16098294?v=3',
  u'html_url': u'https://github.com/alimcodescalers',
  u'id': 16098294,
  u'login': u'alimcodescalers',
  u'name': u'Mahmoud Ali'},
 u'lastname': u'Ali',
 u'phonenumbers': [{u'label': u'main', u'phonenumber': u'+201002881102'}],
 u'publicKeys': [],
 u'username': u'm_flip_flop'}

In [104]: res=client.api.GetUserInformation(user)

In [105]: res.json()
Out[105]: 
{u'addresses': None,
 u'emailaddresses': None,
 u'facebook': {u'id': u'', u'link': u'', u'name': u'', u'picture': u''},
 u'firstname': u'',
 u'github': {u'avatar_url': u'',
  u'html_url': u'',
  u'id': 0,
  u'login': u'',
  u'name': u''},
 u'lastname': u'',
 u'organizations': None,
 u'phonenumbers': None,
 u'publicKeys': None,
 u'username': u'm_flip_flop'}
`

**Comment by robvanmieghem** [comment]
The problem is that the user:admin should also work for the getuserinformation call. Normally the getuserinformation is only used for external services and is not used with the user:admin scope but it should work nevertheless.

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/issues/278 only works for an itsyou.online itself, not for client credentials keys for example.

**Comment by robvanmieghem** [comment]
script used to test:
```
import requests
import json

session = requests.Session()
session.headers['Content-Type'] = 'application/json'

client_id = ''                  #Client ID rob
client_secret = ''

params = {
    'grant_type':'client_credentials',
    'client_id':client_id,
    'client_secret':client_secret
}

resp = session.post('https://dev.itsyou.online:8443/v1/oauth/access_token?',params=params, verify=False)
resp.raise_for_status()
access_token = resp.json()['access_token']
session.headers['Authorization'] = 'token ' + access_token

secondary_resp = session.get('https://dev.itsyou.online:8443/api/users/rob/info', verify=False)
resp.raise_for_status()
print(secondary_resp.content)
```

**Comment by LeeSmet** [comment]
using the test script, it seems that this issue has since been resolved. Probably by e319e34f
