### ISSUE TITLE
iyo-ImprovedIntegration: Organization member authentication error

### ISSUE THREAD

**Issue by waleedhammam** [itsyouonline/identityserver#247]
If you're a member of an organization and then revoked you'll still be a member and authenticated.

**Comment by robvanmieghem** [comment]
@waleedhammam Can you describe the scenario a bit more in detail?

**Comment by waleedhammam** [comment]
after creating an organization and adding members to it.
OK they are allowed to connect and the response will contain the right scope.
let's say you delete a member from the organization he'll still have the right to access and he'll not be revoked
