### ISSUE TITLE
SMS messages are sometimes sent/received with a delay of 10 minutes

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#253]

**Comment by yveskerwyn** [comment]
Reported by @jdelrue from Artilium

**Comment by robvanmieghem** [comment]
We would have to add some more logging and compare that to the logs of the sms service we use

**Comment by LeeSmet** [comment]
Improved some logging, for an example command on how to store (important) logs in a logfile, see [/docs/logging/logfile.md](https://github.com/itsyouonline/identityserver/blob/0.9.10/docs/logging/logfile.md)

**Comment by jdelrue** [comment]
Can you please reopen this? We still have allot of problems with this...
