### ISSUE TITLE
iyo-ImprovedIntegration: staging: can't add github account

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#267]
it redirect to: https://github.com/login/oauth/authorize/?client_id=

staging is currently at version 0.9-beta-5.1-23-g6d068d3

see attached screen shot
![screenshot from 2016-10-12 11-13-53](https://cloud.githubusercontent.com/assets/16098294/19304448/f9f25452-906c-11e6-9833-3aac6bd728d6.png)

**Comment by robvanmieghem** [comment]
Created the staging.itsyou.online github application and configured it in the staging environment.
