### ISSUE TITLE
staging: api documentation is not accessible 

### ISSUE THREAD

**Issue by alimcodescalers** [itsyouonline/identityserver#270]
check url: https://staging.itsyou.online/apidocumentation

staging is currently at version 0.9-beta-5.1-23-g6d068d3

see attached screen shot
![screenshot from 2016-10-12 15-21-55](https://cloud.githubusercontent.com/assets/16098294/19311685/b33d2492-908f-11e6-8ee8-dde132ad1999.png)

**Comment by robvanmieghem** [comment]
And it is in the old UI style

**Comment by robvanmieghem** [comment]
@alimcodescalers good thing you caught this on staging before it went to production!

Can you add it to the manual testscenario's ?

Version with the fix from @LeeSmet has been deployed to staging: 0.9-beta-5.1-30-g5674ded

**Comment by alimcodescalers** [comment]
Done https://github.com/itsyouonline/testing/blob/master/manual_testing/urls_verifications.md
