### ISSUE TITLE
security: XSS in home page

### ISSUE THREAD

**Issue by islamTaha12** [itsyouonline/identityserver#272]
**Description**
I found a XSS vulnerability in the home page. Here is the attack link
https://itsyou.online/error%3CBODY%20ONLOAD=%22alert(window.cookies)%22%3E

**Actual result**
![screenshot from 2016-10-20 11-15-24](https://cloud.githubusercontent.com/assets/17981089/19555501/ba4aada4-96c5-11e6-9d6b-410fd66cc8c4.png)

As you can see, We can load the user cookies. With some evil script, Attacker can hack the user accounts. 

Hint:
You have to use firefox to fire it.

**Comment by alimcodescalers** [comment]
its on staging: https://staging.itsyou.online/error%3CBODY%20ONLOAD=%22alert%28document.cookie%29%22%3E

**Comment by robvanmieghem** [comment]
It's reflective xss and only on the error page but you are right, it is not nice.
Congrats on finding it btw.
There should be a serverside check to validate if the errorpage requested is within the http errorcode range.

**Comment by islamTaha12** [comment]
Thanks Rob.
