### ISSUE TITLE
Received 400 bad request when trying to make a put request to update user's name

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#276]
## function used:

```
    def UpdateUserName(self, data, username, headers=None, query_params=None):
        """
        Update the user his firstname and lastname
        It is method for PUT /users/{username}/name
        """
        uri = self.url + "/users/"+username+"/name"
        uri = uri + build_query_string(query_params)
        return self.session.put(uri, data, headers=headers)
```
## parameters

data = {'firstname' :  'test', 'lastname' : 'test'}

**Comment by LeeSmet** [comment]
https://github.com/Jumpscale/go-raml/issues/170

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/ea3373ca8653ff5e26c8a9b391a18648a96f208b should fix this since the client is now generated using a go-raml version that handles this better.

**Comment by LeeSmet** [comment]
The server expects the arguments to be send as JSON, not query parameters. After you set the token header, go to the `body` tab, then select `raw`. Finally, from the drop down menu that should have appeared, select JSON. This will also automatically add a "Content-Type": "application/json" header to your request. 

![screenshot from 2017-01-09 14-21-50](https://cloud.githubusercontent.com/assets/22023708/21768160/71eb134e-d678-11e6-8451-41c75ea50a09.png)

**Comment by ahmedelsayed-93** [comment]
@LeeSmet 
i followed your steps and the response still Bad Request

![new_put](https://cloud.githubusercontent.com/assets/24386820/21769254/76a96f80-d686-11e6-9d5d-2bc5ebb70426.png)

![scr2](https://cloud.githubusercontent.com/assets/24386820/21769265/81c055e6-d686-11e6-8b90-77e02190d1db.png)

**Comment by LeeSmet** [comment]
You need to write the json in the field, like I did in the screenshot i linked above. So in the second screenshot, in the field that is currently empty, you should write the json representation. Currently you are sending an empty body.
