### ISSUE TITLE
Always recieve a bad request when trying any api on https://staging.itsyou.online/apidocumentation

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#277]
https://staging.itsyou.online/apidocumentation
Example:
![400error](https://cloud.githubusercontent.com/assets/15011431/19674920/f581a87e-9a93-11e6-9243-c4f61f6650fb.png)

**Comment by robvanmieghem** [comment]
Duplicate of https://github.com/itsyouonline/identityserver/issues/241
