### ISSUE TITLE
The api "/users/{username}/info" return empty values

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#278]
![userinfo_right](https://cloud.githubusercontent.com/assets/15011431/19680933/2afd2016-9ab0-11e6-97f3-6839b40599ab.png)

![info_error](https://cloud.githubusercontent.com/assets/15011431/19680921/1da226a0-9ab0-11e6-9d00-5966f4b4d98c.png)

**Comment by robvanmieghem** [comment]
This is indeed a problem when you have the `user:owner` scope.

**Comment by lucasvanhalst** [comment]
This seems to be a duplicate of #246
