### ISSUE TITLE
Can't recover existing account in case password has been forgotten.

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#284]
# Scenario

1- Go to login page and click "FORGOTYOUR PASSWORD?" button
2- Provide a valid username or emailaddress of the account
## Actual Result:

![user_rec](https://cloud.githubusercontent.com/assets/15011431/19727170/f66bde7c-9b96-11e6-80c8-3f403f09f8af.png)
![email_rec](https://cloud.githubusercontent.com/assets/15011431/19727172/f829f5fa-9b96-11e6-9af4-033a136fc817.png)
## Expected Result:

A valid username or email address should be accepted and a recovery email should be sent.

**Comment by LeeSmet** [comment]
has the email address been validated and does the account have any validated email addresses?

**Comment by LeeSmet** [comment]
This is the expected result when the user has no verified email addresses. Also commit 31796345cba8c654ade805b59b91c7e7eeb34c18 should help remedy this as now an email activation link is sent automatically as part of the registration flow
