### ISSUE TITLE
Can create 2 accounts with same email and phone number 

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#286]
- Please prevent creating more than one account with same information
  ![22_user11](https://cloud.githubusercontent.com/assets/15011431/19729879/200809b8-9ba1-11e6-8a18-5ecb4b9f0548.png)
  ![11_user2](https://cloud.githubusercontent.com/assets/15011431/19729861/184e8d0a-9ba1-11e6-8287-ccb44545c614.png)

**Comment by robvanmieghem** [comment]
Is this only for the phone number or also for the email address (both being verified I mean)

**Comment by john-kheir** [comment]
Not sure if i got you.. but the phone number was automatically verified .. and i was able to verify the email as well 
![verify](https://cloud.githubusercontent.com/assets/15011431/19730261/4988ee5a-9ba2-11e6-9b66-ea8bd98ec585.png)

**Comment by LeeSmet** [comment]
An email address should only be verified for one account at the time, i.e if you verify the email for account A, then go and verify it for account B, it should be gone for account A

**Comment by john-kheir** [comment]
@robvanmieghem yes only for phone number, but then i was asked to provide my phone number during login
@LeeSmet you were right when i verified my email address for one account it has been automatically unverified for the other 
@robvanmieghem @LeeSmet  I believe we should prevent the creation of an account with already existing email or phone number from the beginning .. because i can go back and forth between the 2 accounts and verify my email on the account i want to use .. as if i have 2 identities (one at a time)

**Comment by LeeSmet** [comment]
Since the email address and phone number are only verified on a single account at the same time, and valid use cases exist where they might get re-validated on another account, this is intended and not a bug
