### ISSUE TITLE
It's allowed to send an invitation to a user that doesn't have a verified email

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#287]
## Scenario

1- Create a user (andrew) with non verified email (andrew@gmail.com) 
2-  From another account (user=john1) send invitation to andrew using username(andrew)
![andrew_in](https://cloud.githubusercontent.com/assets/15011431/19757738/22fc3ae0-9c2d-11e6-9d4c-86b44c8a2ad1.png)
## Actual result:
- An invitation has been send to andrew
  ![222_invite](https://cloud.githubusercontent.com/assets/15011431/19757528/fab06b16-9c2b-11e6-81ca-35dd8cde1445.png)
## Expected result
- An invitation shouldn't be sent to a user with unverified email

**Comment by john-kheir** [comment]
# Question
The invitation has been sent from an account that doesn't have a verified email also, Is that allowed?

**Comment by LeeSmet** [comment]
The presence of a verified email address is not required to be invited, if you know the username or a validated phone number. Likewise, it's perfectly fine to invite someone if you don't have a verified email address yourself. Currently a verified email address is only required to recover your account if you lose your password. In all other cases, it's just pretty useful to send invites and the likes (as it's probably easier to just send an invite to your friends email address which you know, rather then getting in touch with them and ask for their username, which you might not know e.g.).

**Comment by robvanmieghem** [comment]
This issue is deprecated by https://github.com/itsyouonline/identityserver/issues/299
