### ISSUE TITLE
iyo-ImprovedIntegration: Customize the text on the sign in/up page per organization

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#293]
Currently only the logo can be changed, the text under logo is fixed, and always in English

In order to better set the context to new users it's of critical importance to allow our partners to customize this text

**Comment by robvanmieghem** [comment]
@yveskerwyn Only the text is an easy thing to do. The problem is that the customers might want some some basic markup in the text, in order to prevent XSS, this starts getting complex.

**Comment by robvanmieghem** [comment]
For now, only modification of the text

**Comment by robvanmieghem** [comment]
The text is customisable per language

**Comment by robvanmieghem** [comment]
TODO:
- [ ] Check https://github.com/LeeSmet/identityserver/commit/0393a9b4406bfd2082ae957c400b2a1abfe550bb#commitcomment-20034865
- [ ] Add to the documentation
