### ISSUE TITLE
iyo-ImprovedIntegration: Support for other languages

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#294]
Currently we only support English

**Comment by robvanmieghem** [comment]
In a first version, only Dutch will be added

**Comment by robvanmieghem** [comment]
Also, an optional parameter should be made available for a third party website to pass the preferred the language. If the use explicitly changes the language, this should be stored in the local storage.

**Comment by robvanmieghem** [comment]
TODO:
- [ ] Support the query parameter
- [ ] SMS's are always sent in English
