### ISSUE TITLE
iyo-ImprovedIntegration: Can not access sub organization when being owner of organization

### ISSUE THREAD

**Issue by grimpy** [itsyouonline/identityserver#298]
When another owner of a organization creates a suborganization.
I can not access this organization altough I am owner of the parent organization.

UI shows login screen (which probably shoudl be a screen informing me that I dont have access)

**Comment by robvanmieghem** [comment]
Description of how it should work:
https://gig.gitbooks.io/itsyouonline/content/organizations/organizationownership.html

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/d8105120573e6e6d4531d31752a9993bcb0b4005
Deployed 0.9-beta-6.0-28-gd810512 to staging
