### ISSUE TITLE
iyo-ImprovedIntegration: Invite people into an organisation with an unknown email / phonenumber

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#299]
It is not always easy to know which email addresses / phonenumbers people used on their itsyou.online account.

**Comment by robvanmieghem** [comment]
People should get an invite link and when they follow it but already have an iyo account, can choose to add this to their profile (and is immediately verified off course).

**Comment by lucasvanhalst** [comment]
@robvanmieghem should this be for both email addresses and phonenumbers or only email addresses
