### ISSUE TITLE
Prevent users and organizations from sharing a name

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#303]
Currently, usernames and organization id's can have the same name. We should add some checks to prevent this to avoid confusing the end users

**Comment by robvanmieghem** [comment]
TODO: check if this is the case in the production/staging dataset

**Comment by robvanmieghem** [comment]
Left the detection of duplicates to a new issue:
https://github.com/itsyouonline/identityserver/issues/361
