### ISSUE TITLE
iyo-ImprovedIntegration: Separated page for SignIn and SignUp

### ISSUE THREAD

**Issue by tcai123** [itsyouonline/identityserver#304]
Request from C3 project.

Currently, SignIn and SignUp is using a same page, which is not working for our scenario. Basically, C3 SignIn and SignUp has different workflow and backend logic, so we are expecting to have two separated pages for SignIn and SignUp.

**Comment by robvanmieghem** [comment]
@tcai123  Could you specify a bit more what scenario you would want with the signup?
Also, do you want to prevent users from using the signup button when they are on the login page?

**Comment by tcai123** [comment]
Basically, SignIn and SignUp has different backend logic for our C3 portal, so we prefer to have a separated page for SignIn and SignUp scenario.

Thanks,

Tony Cai /// Sr. Technical Architect
Capris Development, a CentriLogic company
Phone: 647-247-2313
Cell: 647-629-7891
www.capris.com<http://www.capris.com/> | www.centrilogic.com<http://www.centrilogic.com/>
Follow us @CentriLogic<http://www.twitter.com/centrilogic> or on Linkedin<http://www.linkedin.com/company/centrilogic>
