### ISSUE TITLE
iyo-ImprovedIntegration: Add possibility to add a ssh public key to the user profile

### ISSUE THREAD

**Issue by zaibon** [itsyouonline/identityserver#307]
I would be nice to have the possibility for a user to add its public key to its itsyou.online profile

**Comment by robvanmieghem** [comment]
This is present in the data model but is currently not exposed in the UI (nor the api it seems).

**Comment by robvanmieghem** [comment]
A cool extra would be to also integrate github and be able to share those keys as well but let's start with the basics :-)

**Comment by robvanmieghem** [comment]
Deployed 0.9-beta-6.0-28-gd810512 to staging
