### ISSUE TITLE
iyo-ImprovedIntegration: Improve sharing information with organizations

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#312]
Currently an email address and phone number are requested to be shared when joining an organisation. This is not sufficient and also no business rules are in place when this authorisation is revoked.
- [x] It should be possible to configure per organization what information members/owners should share
- [x] We also need a way to indicate if this information is shared only the organization(+owners) or to all members.
- [x] It should also be in the list of notifications of a user when he/she is part of an organization that requests some information to be shared and when he/she is not. Clicking on resolve would allow you to fix this.
- [x] When someone is not sharing this information to an organization he/she is part of, this should be indicated by a ❗️ in the list of owners/members and a tooltip what information is not shared. 

No action to be taken when an organization removes something from it's requested share list.

**Comment by lucasvanhalst** [comment]
Forgot to check the scopes in user /user/info call
