### ISSUE TITLE
iyo-ImprovedIntegration: Possibility to return a jwt in json during the access_token request

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#320]
- [x] Add the implementation
- [x] Update the documentation

**Comment by iwanbk** [comment]
@robvanmieghem just sent a PR for this #319

**Comment by robvanmieghem** [comment]
@iwanbk I know, created a feature for it to make it visible

**Comment by robvanmieghem** [comment]
Documentation: 6e7627597797ecb509dc0e07054bb4100a5a33dd

**Comment by robvanmieghem** [comment]
This is deployed on the staging environment right now, will have other people test their integrations before moving this to production.
