### ISSUE TITLE
iyo-ImprovedIntegration: Unable to use the OAuth 2.0 support in Postman against Itsyou.online

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#321]
After a successful 2FA authentication you get this:
![screen shot 2016-11-23 at 14 17 13](https://cloud.githubusercontent.com/assets/13795109/20563233/edbba01c-b187-11e6-829f-19a54df4ae2c.png)

**Comment by lucasvanhalst** [comment]
Issue seems to be that our service is expecting a 'state' parameter in the access token request, and postman isn't sending it. Postman does send a state param when doing the authorizing though.
Perhaps verifying the state during the access token request is not needed @robvanmieghem ?

**Comment by robvanmieghem** [comment]
@lucasvanhalst Even though I think state is a good practice, we should not enforce it

**Comment by lucasvanhalst** [comment]
Problem is postman _is_ sending a state param during the authorize request:
`GET /v1/oauth/authorize?client_id=testorg&scope=user:name&state=5701830&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code
`
but isn't sending it when doing the `POST /v1/oauth/access_token` request. I don't think we should ignore the state when it was provided in the first request?

**Comment by robvanmieghem** [comment]
Absolutely right

**Comment by lucasvanhalst** [comment]
Then the issue is on postman's side I guess?

**Comment by robvanmieghem** [comment]
Seems like it, can you create a ticket on their side? https://github.com/postmanlabs/postman-app-support/issues

**Comment by lucasvanhalst** [comment]
Done https://github.com/postmanlabs/postman-app-support/issues/2500

**Comment by lucasvanhalst** [comment]
This is now fixed in postman 4.9.0

**Comment by yveskerwyn** [comment]
Cool
