### ISSUE TITLE
Logo contains the 'YOU' text twice

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#339]
<img width="531" alt="screen shot 2016-12-02 at 12 52 14" src="https://cloud.githubusercontent.com/assets/3511318/20833147/5e493a1c-b88e-11e6-9ffb-65c9e5c24ee3.png">

**Comment by robvanmieghem** [comment]
And it currently is totally not sharp.

**Comment by lucasvanhalst** [comment]
[itsyouonline-logo.zip](https://github.com/itsyouonline/identityserver/files/631527/itsyouonline-logo.zip)
Can someone with photoshop update the logo

**Comment by robvanmieghem** [comment]
@FastGeert Seriously, how long can changing some text and exporting it in a higher resolution take?

**Comment by FastGeert** [comment]
Will ask Gert nicely tomorrow.

**Comment by robvanmieghem** [comment]
@FastGeert Ping
