### ISSUE TITLE
Cancelling invitations.

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#350]
I just made an invitation from the wrong group, and would like to cancel it, but this is not possible at the moment.

![image](https://cloud.githubusercontent.com/assets/15246294/20865014/8a5d43fe-ba06-11e6-929a-a4061ad9d3f3.png)

**Comment by LeeSmet** [comment]
Closed by 1efc1742658fc715eb4f51006c98853bc6177bd4
