### ISSUE TITLE
If a user has not logged in to itysou.online before, an authorize flow should go to the registration screen instead of the login

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#358]
Local storage or maybe a cookie, see what is the easiest thing to do.

**Comment by LeeSmet** [comment]
The parameter to use during the OAuth login flow is `prefer=register`. If the param is set, and localstorage does not contain a `hasLoggedIn` item, the client will be redirected to the register page and the prefer parameter will be removed. If the `hasLoggedIn` item is set in localstorage, the prefer parameter will be ignored
