### ISSUE TITLE
It's allowed to create an organization with a "blank" name

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#366]
if a user makes an oganization, and enters only whitespaces in the input field for the organization name, the name validation will pass, as long as the amount of whitespace is within the accepted amount of characters. There is then an organization with name "     ".
After creation, if the user leaves the organization page and then tries to navigate there again, a Status 500 - Internal server error gets thrown

**Comment by robvanmieghem** [comment]
Since when is whitespace allowed?

**Comment by lucasvanhalst** [comment]
Since always

**Comment by lucasvanhalst** [comment]
d7cbbeb
