### ISSUE TITLE
Accepting invitation while giving authorization fails

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#378]
During an OAuth2 login flow, if the user gives authorization and a memberof scope is requested, an invite for this organization will be accepted (if the user is invited and thus not an actual member yet). However, when clicking on the authorize button, the user will get redirected to a standard login page (and thus failing the OAuth2 flow).

**Comment by robvanmieghem** [comment]
This fix has been cherry-picked to the 0.9.9 branch
