### ISSUE TITLE
Make pages more mobile friendly

### ISSUE THREAD

**Issue by RubenMattan** [itsyouonline/identityserver#383]
![2016-12-21 14 08 13](https://cloud.githubusercontent.com/assets/1122760/21392306/85d0d1de-c78f-11e6-838c-da1c179c96af.png)

![2016-12-21 14 10 10](https://cloud.githubusercontent.com/assets/1122760/21392360/c29b225e-c78f-11e6-8370-6ce4c9e0184e.png)

**Comment by robvanmieghem** [comment]
Clearly the header is not mobile friendly
