### ISSUE TITLE
Dealing with lots of organizations is not very user friendly

### ISSUE THREAD

**Issue by grimpy** [itsyouonline/identityserver#386]
When dealing with a big organization with lots of suborganizations things become messy.

https://itsyou.online/#/organizations
is not sorted and hard to find things in possible to make vertical tree?
Organizations with explicti membership or as part as organization should be visible here.

![161225_132313](https://cloud.githubusercontent.com/assets/143869/21470916/50da2070-caa5-11e6-8620-d7f7e983770a.png)

Organization structure is hard to navigate.
![161225_132347](https://cloud.githubusercontent.com/assets/143869/21470917/64248c38-caa5-11e6-8c89-14c5ef9aed72.png)

**Comment by LeeSmet** [comment]
Closing this in favor of the linked issues
