### ISSUE TITLE
can't  use forgot  password and doesn't send code to login to itsyouonline

### ISSUE THREAD

**Issue by Dinaamagdy** [itsyouonline/identityserver#391]
## scenario 1 

- try to login to itsyouonline by my user name 
## result
- it doesn't send code to phone  so can't login 

![selection_027](https://cloud.githubusercontent.com/assets/24386802/21611415/726a2406-d1d5-11e6-8aaf-90764a230d99.png)

## scenario 2
- try to use forgot  password 
## result 
-  I got that user doesn't exist  as shown on the following screenshot

![2](https://cloud.githubusercontent.com/assets/24386802/21611376/3fa42742-d1d5-11e6-90fc-45c309ee3614.png)

- And when try to register again with the same username , I got that user already exist as shown on the following screenshot

![1](https://cloud.githubusercontent.com/assets/24386802/21611382/445ec148-d1d5-11e6-96e4-244b3d84128e.png)

**Comment by LeeSmet** [comment]
The user already exsists but can't reset password is  caused by lack of validated email address
