### ISSUE TITLE
USER API - Error when trying to add apikey with label already exists

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#402]
### Steps
- Create apikey 
- Create another apikey with same label of the previous one 

### Actual result
- response status : 201 
-  there are two apikeys with same label 

![apikey](https://cloud.githubusercontent.com/assets/24386820/22019839/dd5d4d68-dcbd-11e6-8f69-e9d2df1d23fc.png)

### Expected reuslt
 response status : 409 
The new label is already used

**Comment by LeeSmet** [comment]
Fixed by  620aafe
