### ISSUE TITLE
Unauthorized user can call all APIs successfully

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#411]
### Steps
- Create user **test_api_1**   (for example)
- Create new api key for **test_api_1**
- Create another user **test_api_2**   (for example)
- Use the **client_id** and the **client_secret** of the user **test_api_1**  to generate access token
then use this access token to send get, put, post , delete requests for user  **test_api_2** 

### Actual result
Unauthorized user can call all the APIs successfully

![screenshot from 2017-01-19 18-11-53](https://cloud.githubusercontent.com/assets/24386820/22114779/51cbf62a-de73-11e6-8842-9c67a9da85b4.png)

### Expected result
401 Unauthorized

### Version
v0.9.9-30-gf150f6d

**Comment by robvanmieghem** [comment]
@ahmedelsayed-93 Are you sure there are not authorizations? This call should not even work like this:
https://github.com/itsyouonline/identityserver/issues/434

**Comment by ahmedelsayed-93** [comment]
@robvanmieghem 
user **test_api_1** was authorized and i used its access token to call apis for user **test_api_2**

![fg](https://cloud.githubusercontent.com/assets/24386820/22624585/049def02-eb89-11e6-8468-c0d8aa094535.png)

**Comment by robvanmieghem** [comment]
Caused by fa9ef9231e56577d291fc4457cf96ec8f561fd03

**Comment by robvanmieghem** [comment]
thanks @ahmedelsayed-93 for pointing out this critical issue
