### ISSUE TITLE
USER API - [GET] Info returns Internal Server Error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#412]
GET/users/{username}/info

![500-info](https://cloud.githubusercontent.com/assets/24386820/22247532/fd2f4882-e242-11e6-9640-713df45af7a1.png)

**Comment by LeeSmet** [comment]
@ahmedelsayed-93 can you show the headers you used in the request?

**Comment by robvanmieghem** [comment]
@ahmedelsayed-93 Is this a duplicate of https://github.com/itsyouonline/identityserver/issues/434 (or vice versa) ?

**Comment by ahmedelsayed-93** [comment]
@LeeSmet 

![image](https://cloud.githubusercontent.com/assets/24386820/22624545/b69a314a-eb87-11e6-80d1-dd7ce99d5cde.png)
