### ISSUE TITLE
USER API - [DELETE] Error in organization/{globalid}/leave response code

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#414]
### Steps
- call this api  ```DELETE/users/{username}/organizations/{globalid}/leave ``` with fake username

### Actual result
response code : 204

![leave](https://cloud.githubusercontent.com/assets/24386820/22249831/4a723d02-e24d-11e6-9e0e-09385727dd29.png)

### Expected result
response code : 404

![leave-response](https://cloud.githubusercontent.com/assets/24386820/22249864/6d7f0884-e24d-11e6-8d03-d8c4c16cf43b.png)

**Comment by LeeSmet** [comment]
As you can't have access rights to call api's for a non existing user (since he doesn't have api keys), the main problem here was #411. With this being resolved, all that needs to be done is update the documentation for the 404 response code
