### ISSUE TITLE
IE11 - Message needed when trying to enter invalid login + password on the Portal page

### ISSUE THREAD

**Issue by jdelrue** [itsyouonline/identityserver#417]
**Description**
Use IE11
Surf to: http://portal-tst.artilium-africa.com/
You are redirected to ItsYou.Online
 
Enter log in = "bla"
Enter password= "bla"
 
Click Login button
 
Expected result
User gets warning message about the invalid credentials
 
Actual result
Nothing happens
 
![image](https://cloud.githubusercontent.com/assets/1687505/22324100/72c5a31a-e3a7-11e6-9f79-7f94a81ca93f.png)

**Comment by LeeSmet** [comment]
This is fixed by 93dd26a2adc800bcebc91b6cbc0ec61e15fec3a8
