### ISSUE TITLE
tsYou.Online showing error when trying to retrieve password while providing correct username or email address

### ISSUE THREAD

**Issue by jdelrue** [itsyouonline/identityserver#418]
**Chrome**
Suft to: http://portal-tst.artilium-africa.com/
You are redirected to ItsYou.Online
Click 'Forgot your password'
Enter correct username.
 
Expected:
User receives an error saying that e-mail address is not verified.
 
Actual:
User receives an error saying that a user could not be found.
 
![image](https://cloud.githubusercontent.com/assets/1687505/22324175/fc3ef9d4-e3a7-11e6-88d2-a738d118f166.png)

**Chrome**

Same behaviour when entering the (correct) email address:

Suft to: http://portal-tst.artilium-africa.com/
You are redirected to ItsYou.Online
Click 'Forgot your password'
Enter correct email address.

![image](https://cloud.githubusercontent.com/assets/1687505/22324216/47708562-e3a8-11e6-81db-6133bc6eebbc.png)

**Comment by FastGeert** [comment]
Error message should be more detailed / clear
