### ISSUE TITLE
Question: which organizations are shown?

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#433]
As you can see in the last/bottom screenshot I'm owner of the greenitglobe/environments organization...

Why can't I see this in the top organizations view, while I can see greenitglobe/environments/uk-g8-1? See first screenshot.

In order to access greenitglobe/environments I currently need to click through greenitglobe/environments and then use the breadcrumb navigation to get to the greenitglobe/environments; see second/middle screen shot

Is this by design? Why? Wouldn't it be better to see the top level organizations where I'm owner? 

![screen shot 2017-02-03 at 09 24 37](https://cloud.githubusercontent.com/assets/13795109/22584454/bec6b604-e9f2-11e6-9acb-ed8649f73a1a.png)

![screen shot 2017-02-03 at 09 24 47](https://cloud.githubusercontent.com/assets/13795109/22584459/c363871e-e9f2-11e6-904a-8f4aad5b17a0.png)

![screen shot 2017-02-03 at 09 24 54](https://cloud.githubusercontent.com/assets/13795109/22584462/c7749ce4-e9f2-11e6-90ad-56de6c3ca1a2.png)

**Comment by LeeSmet** [comment]
This is not intended, however it should be solved in issue #387, #388, and #390
