### ISSUE TITLE
Getting a jwt fails if the user didn't authorize one of the scopes

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#436]

**Comment by robvanmieghem** [comment]
The problem is the following (as stated in the documentation):
```
...the scope parameter needs to be given to prevent consumers to accidentally handing out `user:admin` or `organization:owner` scoped tokens to third party services.
```
But since you do not know the authorized scopes there is no way to know which ones to include (besides making a roundtrip over a normal access token).
