### ISSUE TITLE
Organizations API - Error when trying to update non-existing dnsname

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#444]
API : ```PUT /organizations/{globalid}/dns/{dnsname}```   
- Call this api with non-existing dnsname

### Actual result
response : 201
### Expected result

![image](https://cloud.githubusercontent.com/assets/24386820/22737787/559d54ca-ee0d-11e6-8319-a28f4952ae59.png)

**Comment by LeeSmet** [comment]
Fixed by e326073f40b78886f6e5c3bb30f9abb5b688e719
