### ISSUE TITLE
Organizations API - Error when trying to delete organization which still has child organizations

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#447]
### Steps 
- Create organization (**org_1**) 
- Create sub-organization (**org_1_1**)
- remove the parent organization (**org_1**) using api: ```DELETE organizations/{globalid}```

![image](https://cloud.githubusercontent.com/assets/24386820/22780221/a6bd66d8-eec6-11e6-9e0c-9438972d0eb1.png)

### Actual result 
Organization org_1 was deleted 

![image](https://cloud.githubusercontent.com/assets/24386820/22780251/bb7ee056-eec6-11e6-8a59-66d924e9e912.png)

### Expected result
response : ``` 422 ```

![image](https://cloud.githubusercontent.com/assets/24386820/22780511/aa73cdfc-eec7-11e6-8c4a-8726ca16e8d1.png)

**Comment by robvanmieghem** [comment]
The documentation should be updated for this
