### ISSUE TITLE
Organizations API - any user can create organizations for other users

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#449]
### Steps
- Create user (**test_api_1**)
- Create new user (**test_api_2**)
- Authorize user **test_api_1** 
- Call this api : ```POST organizations``` using **test_api_1** access token

with **Body**
<pre>
{
  "dns": [],
  "globalid": "org-12",
  "members": [],
  "owners": [
    <b>"test_api_2"</b>
  ],
  "publicKeys": [],
  "secondsvalidity": 0,
  "orgowners": [],
  "orgmembers": [],
  "requiredscopes": [],
  "includesuborgsof": []
}
</pre>

### Actual result
user **test_api_1** created organization and made user **test_api_2** owner
response : ```201```

![mmm](https://cloud.githubusercontent.com/assets/24386820/22784474/d76ce17a-eed8-11e6-92ed-4588f310e03c.png)

### Expected result
response : ```403```

**Comment by robvanmieghem** [comment]
@ahmedelsayed-93 This is currently deployed on staging, if you verify, I'll push to production

**Comment by ahmedelsayed-93** [comment]
@robvanmieghem 
i think a part of the issue still exist 
because the response code still 201, and it should be 403 or 404
 
![image](https://cloud.githubusercontent.com/assets/24386820/22791852/62cff896-eef3-11e6-9cf3-8097d7372b33.png)

**Comment by robvanmieghem** [comment]
@ahmedelsayed-93  Well, actually I don't look at what is present in the owners, members, orgowners or orgmembers fields. They are all blanked out and the current user is added to the owners list.

**Comment by ahmedelsayed-93** [comment]
ok we can close this issue

**Comment by robvanmieghem** [comment]
@ahmedelsayed-93 good catch by the way

**Comment by ahmedelsayed-93** [comment]
@robvanmieghem  thanks
