### ISSUE TITLE
Organization API - Internal server error when updating organization info

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#450]
API : ``` PUT organizations/{globalid} ```

![image](https://cloud.githubusercontent.com/assets/24386820/22785656/e608f296-eedd-11e6-9bdf-f0b2d33460f2.png)

**Comment by LeeSmet** [comment]
Seems like saving an entire organization in db is not implemented yet

https://github.com/itsyouonline/identityserver/blob/master/db/organization/db.go#L665

**Comment by FastGeert** [comment]
Remove this api call and update documentation
