### ISSUE TITLE
Internet explorer 11: TypeError - object doesn't support property or method 'startsWith'

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#451]
Steps to reproduce:

1. Use Internet Explorer 11 (havn't tested lower version)
2. Navigate to itsyou.online
3. Fill in an incorrect username/password and click login
4. No feedback is given to the user

![gig internet explorer iyo](https://cloud.githubusercontent.com/assets/25665449/22787702/7462ba3c-eedd-11e6-8a77-556bc8066307.PNG)

Open the developer tools and navigate to the console.
TypeError is displayed.

![gig internet explorer iyo dev console](https://cloud.githubusercontent.com/assets/25665449/22787692/6ea92054-eedd-11e6-9374-05df40f809f0.PNG)

The documentation of the JS library states that IE is not supported for the method startsWith (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)

The same goes for retrieving a password based on username (email works)

![iyo internet explorer recover password](https://cloud.githubusercontent.com/assets/25665449/22787931/4bce847e-eede-11e6-8b53-f4d5463b4b06.PNG)

**Comment by robvanmieghem** [comment]
@n-dury Thank your for the detailed bug report
