### ISSUE TITLE
IYO Registration form: E-mail field allows invalid e-mail

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#455]
Steps to reproduce:

1. Navigate to Itsyou.online
2. Click register
3. Fill in a non-existing username
4. Fill in a **non-valid** e-mail address (e.g. tester@a)

**Expected behavior**
Validation should happen on the e-mail field.

**Actual behavior**
Validation accepts invalid e-mail address and moves on to 2factor auth when filling in a password. 

![iyo email validation](https://cloud.githubusercontent.com/assets/25665449/22930428/6d315ac0-f2c0-11e6-975e-e0a11b78787c.PNG)

**Tested using:**
Mozilla Firefox 51.0.1
Microsoft Edge 38.14393.0.0
Google Chrome 56.0.2924.87
Internet Explorer 11

**Comment by FastGeert** [comment]
Add a simple liberate regex check

**Comment by LeeSmet** [comment]
both on register page and on profile page

**Comment by LeeSmet** [comment]
Still errors concerning capitals
