### ISSUE TITLE
IYO User Management: A user cannot recover/reset password

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#456]
**Steps to reproduce**

1. Make a IYO account
2. Validate the e-mail address.
3. Log out of the account and navigate to the login page
4. Click "Forgot password"
5. Enter the e-mail address coupled to your IYO account
6. An e-mail is received, click the link

**Expected behavior**
User is presented with a form where he/she can reset his/her password.

**Actual behavior**
User is redirected to IYO login page instead of a page where he/she can reset his/her password.

**Comment by n-dury** [comment]
Hello IYO,

I am requesting to re-open this ticket.
It is now possible to enter an e-mail address to use the "recover password" functionality however **no email is received**.

Kind regards

**Comment by LeeSmet** [comment]
Hi, I just checked myself with both a username and an email address and i did in fact receive the email on both occassions. Could you please provide some more details so we can try to replicate this issue?

**Comment by LeeSmet** [comment]
Turns out the mails ended up in the spam folder
