### ISSUE TITLE
USERS API - GET /users/{username} response doesn't contain expire item

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#467]
API : ```GET /users/{username}```

### Actual result
![image](https://cloud.githubusercontent.com/assets/24386820/23102897/48ed72ae-f6ba-11e6-96bc-109b31ca28eb.png)

### Expected result
![image](https://cloud.githubusercontent.com/assets/24386820/23102919/832e6446-f6ba-11e6-8d9e-8dc7c2ac1228.png)

**Comment by LeeSmet** [comment]
The `expire` item is optional in the response. Notice how some fields are marked `required` whereas `expire` is not
