### ISSUE TITLE
Don't send invitations to user if user is already part of a sub-organization

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#476]
Example: user is member of `main_organization.sub1.admins`
If the user is added to the organization `main_organization.sub2.admins`, it shouldn't send an invite but immediately add the user.

It should only send an invite if the user is not part of any (sub) organization of `main_organization`
That way we don't have to annoy the user with invites every time we add them to a different sub-organization.

**Comment by LeeSmet** [comment]
For suborganization invites, if the useris already a member or owner in a parent organization, see #619. In case of access management, consider using the grants that will be implemented by #620 once the 1.0.0 release lands

**Comment by LeeSmet** [comment]
Moved to 1.0.0 milestone since this issue is solved by the 2 linked issues above, which are also on the 1.0.0 branch
