### ISSUE TITLE
A user cannot recover his password using his username

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#479]
1. Create an ItsYouOnline account.
2. Validate the account.
3. Log out of the account and navigate to https://itsyou.online/login#/
4. Click "Forgot your password".
5. Enter the username of the previously created IYO account.
6. POST the form

**Expected result**
The user receives an e-mail with a new password / URL to change password
**Actual result**
The user is presented with an error "A user with this username or email address could not be found"

**Comment by LeeSmet** [comment]
Password recovery can only be done with validated usernames, this has currently been resolved by the addition of the validate email button on the login page that sends validation emails for registered email addresses to the user should he or she not have a validated email at the time
