### ISSUE TITLE
Add a Display Name for an organization

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#486]
As part of the login experience users will see the organization name, in the below screenshot that is lci. In stead of showing the organization name we should who a "user friendly" display name, that can be set in customization section of an organization.

<img width="1465" alt="screen shot 2017-03-28 at 10 33 03" src="https://cloud.githubusercontent.com/assets/13795109/24397643/36af9cde-13a7-11e7-8a4d-171dc385a45f.png">

**Comment by LeeSmet** [comment]
Duplicated by #487
