### ISSUE TITLE
Please change "Login" to "Username" on the login page of IYO

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#492]
Hello,

A customer of us has requested to change the text "Login" to "Username" on the IYO login page.
Please change the placeholder on the username field currently displayed "Login" to "Username"

![afbeelding](https://cloud.githubusercontent.com/assets/25665449/25268087/af319d32-2677-11e7-92b4-f3d153d93a71.png)

Kind regards

**Comment by LeeSmet** [comment]
As we also allow users to log in with their verified email addresses or phone numbers, changing the text to just Username does not seem to be the best solution. We can however change it to something like "Username, Email address or phonenumber".

@n-dury  toughts about this solution?

**Comment by n-dury** [comment]
@LeeSmet Hi lee, this solution would be just fine.

Thanks in advance
