### ISSUE TITLE
Request to alter registration flow

### ISSUE THREAD

**Issue by n-dury** [itsyouonline/identityserver#496]
Hello,

We have a customer that made the following remark:

> It is counterintuitive when registering an itsyou.online account one has to manually log in to his/her profile and verify his/her e-mail address.
> It would be much more efficiënt that an activation e-mail is sent to the e-mail listed when the user has registered. 

That way a customer that has not clicked the link in the e-mail, but has forgotten his/her password can still verify his or her account by retrieving the initial e-mail activation link.

Is it possible to forsee an implementation for this?

Kind regards

**Comment by robvanmieghem** [comment]
Qualifying this as a bug since it's bad user experience.

**Comment by n-dury** [comment]
Hi,

Is it possible to provide a status update regarding this issue?

Kind regards
