### ISSUE TITLE
It's cumbersome that the country-code must be entered manually with the phone number

### ISSUE THREAD

**Issue by rvanoverbeke** [itsyouonline/identityserver#498]
Most people are used to give out their phone number to people in the same country, so they might not even be aware of country-codes.
Apparently the error message that a country-code is required doesn't always appear either

So at least this message should be shown at all times and only turn to red if the country-code is missing.
It would be ideal if the user should just select his country from a list, and the country the user is in could be derived from the request, and used as a default.

**Comment by LeeSmet** [comment]
since all available components that seem to add some kind of country drop down witch countries and their phone codes seem to support on JQuery or some other kind of framework we are currently not using, we'll need to implement something ourselves.
