### ISSUE TITLE
2-Factor authentication is not working in registeration

### ISSUE THREAD

**Issue by serboctor** [itsyouonline/identityserver#499]
When registering a new account, I choose 2Factor authentication because I never receive the sms. I scan the 2D barcode and enter the generated code but I keep getting "An invalid code was given".

**Comment by LeeSmet** [comment]
Just tested this and 2FA seems to work as expected.

Could you please try to sync the time server for your authenticator app and provide some more information? (scanning app, are the server and username correct in the authenticator etc...). This should help us to try and recreate the problem

**Comment by serboctor** [comment]
The problem was in my phone clock. It was a couple of mins off. I registered successfully.
