### ISSUE TITLE
Keep session

### ISSUE THREAD

**Issue by nbabenko** [itsyouonline/identityserver#501]
Make IYO to keep session.
Its too much annoying to relogin several times per day.
You can set default 5 days.
And add ability to change in settings.

**Comment by LeeSmet** [comment]
While it is indeed annoying that you might need to log in multiple times per day, especially with the sms, It should be noted that there having an extended active session is not secure. If we keep the session active for 5 days, then we might as well remove 2FA all at once. Keeping the session open would also mean that users will have multiple sessions open i.e. one on their pc in the browser, on on their mobile (this is one is a huge security hole), ...
