### ISSUE TITLE
itsyou.online opens in russian when accessing from ibiza

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#509]
![image](https://user-images.githubusercontent.com/15246294/27080085-a820708a-503a-11e7-9b85-0b0c1677995b.png)

**Comment by LeeSmet** [comment]
Please verify the issue by providing the results when opening ItsYou.Online in an incognito page (or clearing the browser cache and local storage)

**Comment by LeeSmet** [comment]
User changed IYO language previously and forgot to change it back.
