### ISSUE TITLE
Some old users can't log in to staging anymore

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#511]
Old user passwords are rejected. after creating a new user, this user can log in

**Comment by robvanmieghem** [comment]
@LeeSmet Which user is no longer able to log in?

**Comment by LeeSmet** [comment]
Mutliple (but not all ) of my test users, some russian test users... etc

**Comment by LeeSmet** [comment]
Seems like the main cause here was a misunderstanding about the separate database on staging and production
