### ISSUE TITLE
Link in SMS message when registering does not work

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#521]
![image](https://user-images.githubusercontent.com/15246294/27907341-91e11d00-6247-11e7-923c-f461b7b0136f.png)

**Comment by LeeSmet** [comment]
Link in the message is correct when send on the server, however it appears to be truncated by cmtelecom for some reason

**Comment by LeeSmet** [comment]
As this issue is directly related to the cm telecom provider, which we are not going to use, this is no longer relevant
