### ISSUE TITLE
inviting people based on email did not work for me

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#526]
- ask also Nickolay
- they get email then they get a page but no-where the invitation could be accepted
- how does this work if multiple emails or tel nr's be used, will it properly identify the right account if it already exists, can a user overrule that he already exists under other email?

**Comment by LeeSmet** [comment]
By "they get a page" I assume the folowing page: 

![screenshot from 2017-07-17 14-44-16](https://user-images.githubusercontent.com/22023708/28268901-58747ea6-6b00-11e7-8c56-0a0dc28fb1a7.png)

If so, the invitation is accepted continuing with either of the two buttons. In either case, the email address or phone number is validated should it not have been validated already in the meantime

**Comment by despiegk** [comment]
thats how it should be, but wasn't

**Comment by FastGeert** [comment]
@LeeSmet cannot trace what went wrong. Suspects it might have been a connection failure or maybe a cloudflare caching issue.

**Comment by LeeSmet** [comment]
Unable to replicate, will close for now
