### ISSUE TITLE
re-organize milestones & check issues

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#533]
- 0.9.14 needs to be delivered asap and needs to be enough to allow telegram integration 
  - check with holidays
  - needs to be user friendly enough to be used for our ITO & hosters
- define 1.0 and check deliveries & timing (< end summer)
  - first production release

**Comment by dvorkbod** [comment]
Issues brought up and communicated with Kristof, 1.0 is being specced right now by Lee. Closing this now.
