### ISSUE TITLE
username less account registration [16h+16h]

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#545]
In first screen replace username with phone number:
![image](https://user-images.githubusercontent.com/15246294/28571726-87d81442-7144-11e7-82d0-e91a83e7f3d5.png)

If we already have phone number we can omit the two factor AUTH step, and replace it with validating the phone number and email address:
![image](https://user-images.githubusercontent.com/15246294/28571040-36b21692-7141-11e7-8c16-0170ac8fef51.png)

> **Remark**: via query parameter we can define which fields are required to be validated. Need at least one that need to be validated at once.

# Issues with this approach:
## Re-use of phone numbers by telco providers
In case a person looses control over his last validated phone number in IYO, and somebody else validates this phone number on his account, the person needs to be warned that he does not have a validated phone number in his IYO account left, and that that might cause him to loose control over his IYO account.
## Usernames in IYO UI
All displaying of usernames must be replaced by the user's name or phone number or email address if the previous is not present in the account.

**Comment by LeeSmet** [comment]
In the current implementation, the phone number must be validated.
Email validation is required if: 
 - user is registering to iyo (not doing oauth flow)
 - user is in oauth flow and the organization requests the `user:validated:email` scope
 - the `requirevalidatedemail` queryparameter is set
