### ISSUE TITLE
Store public key in IYO account + writescope [16h]

### ISSUE THREAD

**Issue by FastGeert** [itsyouonline/identityserver#546]
Data to stor along with a public key:
- public key
- label
- timestamp
- comment (eg, Key generated by Threefold app)
- crypto algorithme

**Comment by LeeSmet** [comment]
writescope: user:key:label:write. a read only scope does not make any sense if the key is only exposed to the org that writes it in the first place imo

keys should be stored in a key value map with the label as key and the key + data as value, and this map should be a value linked to the organization that reads/writes it

**Comment by LeeSmet** [comment]
Will need a database migration to change the current publickkeys on the user to ssh keys

**Comment by LeeSmet** [comment]
We will remove the validation from the existing publickeys to accomadate all keys (i.e. remove validation specific for sshkeys). Special apis to be implemented for organizations to write keys - keys will be hidden for the user and can not be deleted or updated. Only GET and POST are available (for the organization).
label form: `{globalid}:{label}` where `{globalid}` is the globalid of the organization and `{label}` is the label given to the key by the organization.
