### ISSUE TITLE
Forgot password - unable to restore using phone number?

### ISSUE THREAD

**Issue by dvorkbod** [itsyouonline/identityserver#556]
When claiming I forgot my password, I was not able to restore my account using just my phone number. I would like to be able to restore my account using just my phone number, as I may have multiple email addresses and I don't want to go and figure out which one I used to register on IYO. Not sure if this should be supported or not, it just seems "off" not to have this feature.
![screenshot_2017-08-04-16-13-28](https://user-images.githubusercontent.com/26708761/28973654-2f752036-7934-11e7-904a-e6ec3356476c.png)

**Comment by LeeSmet** [comment]
When a phone number is implemented, an email should be sent to the verified emails of the user (not a message to the phone number). This way a potential attacker needs to have both access to the email account and telephone
