### ISSUE TITLE
Drop full name support to identify other users from the ui

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#557]
Currently some api calls return a Memberview object. This contains a useridentifier and a username, but replaces the old username string. (as using the full name as user identifier is not possible). I feel it would be best to revert this and only allow verfied phone number and email addresses for now. this way we can continue to use string fields (thus remaining backward compatible). Becuase names don't map 1-1 with user(names), we also need to expose the username in the api, so its not really hidden from the user.

Using verified info, we can make the change almost completely in the backend by substitituting usernames with a piece of verified user info. Support for this in the user api (using verified info as user identifiers in api urls) has already been impelented. a similar method can then be implemented and applied to all incomming json with usernames, and a reverese method for all outgoing json with usernames.

Although this could be pushed to 1.0.0 release, it would be best to have this asap to avoid technical debt and make sure production compatibility is never broken

**Comment by lucasvanhalst** [comment]
So in short get rid of memberview and put an email address or phone number in place of the it?

**Comment by LeeSmet** [comment]
yes, also make sure the name of the field is reverted to the original (if it is changed, I think there is maybe 1). Existing integration can then continue to function properly

**Comment by lucasvanhalst** [comment]
Should we prefer email addresses over phone numbers? Because a list of phone numbers in the organization overview isn't telling me much..

**Comment by lucasvanhalst** [comment]
This will also require the organization api to be refactored: updating organization role, removing a user, ...
