### ISSUE TITLE
Email addresses are case sensitive

### ISSUE THREAD

**Issue by dvorkbod** [itsyouonline/identityserver#562]
Email address is case sensitive in login and in "forgot my pwd"

If we move to convert addresses entered to lowercase, we need to make sure we don't break functionality for existing users who registered with uppercase in their email.

**Comment by LeeSmet** [comment]
Case sensitivity has already been removed in the login form and register form in previous updates (more than 2 months ago, login even longer). The only real affected field here is "forgot my pwd". Given this, there should be no harm in making this field case insensitive now imo

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
