### ISSUE TITLE
Typos in forms

### ISSUE THREAD

**Issue by dvorkbod** [itsyouonline/identityserver#564]
Concerning:
identityserver/siteservice/website/components/login/views/loginform.html
identityserver/siteservice/website/components/registration/views/registrationform.html
identityserver/siteservice/website/assets/i18n/en.json

The message

"Dear {{externalsite}} customer, We make use of the independant ItsYou.Online identity management system to highly protect the access to your {{externalsite}} products. Please login to your ItsYou.Online account to complete the {{externalsite}} onboarding process."

I would replace by

"Dear {{externalsite}} user, access to {{externalsite}} services is managed by the ItsYou.Online identity management system. To proceed, please login or register at ItsYou.Online.

Most importantly, we should remove "independant" and "highly protect", as these are wrong or sound not very professional.

**Comment by dvorkbod** [comment]
Alternative rewording, either is fine for me:
"Dear {{externalsite}} user, access to {{externalsite}} services is managed by  the ItsYou.Online identity management system. Please login or register at ItsYou.Online to complete the {{externalsite}} onboarding process."

**Comment by dvorkbod** [comment]
Seems to be active again, at least when trying to sign up at new.threefoldtoken.com.

**Comment by LeeSmet** [comment]
currently still on staging, threefoldtoken and gig.tech log in via production

**Comment by dvorkbod** [comment]
Whoops. I dun goofed. My apologies.
