### ISSUE TITLE
Fix 'publicKeys' in user information api

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#566]
Every property currently doesn't have any capitals in its name except for publicKeys
Change it to `publickeys` (without capital K) to be consistent with the rest of the api

**Comment by LeeSmet** [comment]
Reverted this issue, as it feels better to maintain consistency throughout the remainder of the codebase, than to remain consistent for the naming in this one api call and break consistency with the same item in other apis
