### ISSUE TITLE
Need mobile friendly layout when accessing itsyou.online on a mobile device

### ISSUE THREAD

**Issue by RubenMattan** [itsyouonline/identityserver#57]
When authenticating via Rogerthat is UI is not mobile friendly see screenshot

![screen shot 2016-05-11 at 15 11 13](https://cloud.githubusercontent.com/assets/1122760/15182008/a12a56f4-178a-11e6-91ad-ce504f0b2095.png)

**Comment by lucasvanhalst** [comment]
![screenshot_2016-05-13-13-36-54](https://cloud.githubusercontent.com/assets/6652304/15246822/0f583070-1910-11e6-9e2d-cbee7a685ff7.png)
this also shouldn't be happening
