### ISSUE TITLE
error when I tried to accept invitation

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#574]
![image](https://user-images.githubusercontent.com/6021844/29278151-26bb982a-8114-11e7-95d0-ee19cf2040c3.png)

![image](https://user-images.githubusercontent.com/6021844/29278308-a0094a2e-8114-11e7-8de2-c6a5fd13e258.png)

**Comment by LeeSmet** [comment]
Unable to reproduce, also since some of the invite code changed, I will close this for now
