### ISSUE TITLE
IYO GUID feature

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#581]
- only needed from API
- allow any APP (API client linked to organization) to request a unique GUID for a user or organization
- only this APP can request which user is behind the GUID
- each ORG can ask max 10 of these unique GUID's for 1 specific user or org
- there is also feature which allows APP to store some data behind this GUID in IYO, this is just binary info & only means something for the APP (max size = 1kb), only APP can retrieve if it also knows the GUID.

## e.g. use case tokens in TF app
- we register info on blockchain e.g. tierion.com but we don't want to put email or other identifiable ID
- this allows the APP (which is org with API client) to create a link between GUID and a user or organization and register that way
- if ever needed this APP can retrieve the user ID but only this APP

## use case for the data
- keep track of metadata relevant to this user
- e.g. imagine app is storing coin info in the blockchain, it needs to be able to remember previous registrations for this user (or a link to the previous one so the app can walk back). can do this as e.g. a json in this data field

## other use case
- register info in Zero-Tlog server, when Tlog server finishes, register the hash & other relevant info in tierion (encrypted using the IYO GUID) which is only known by the APP
- this allows the APP to keep track of lots of info which is stored in Zero-STOR through TLOG server & can be used for full audit trails

**Comment by FastGeert** [comment]
@despiegk, do we really need this feature. I think we can achieve exactly the same by using an hmac of a secret only known by the app and the username.

**Comment by LeeSmet** [comment]
@despiegk What is the relevance for this feature? To me it feels like a GUID (or something similar) is just some random data we generate, i.e. it has no real (personal) value for a user, unlike all the other info we keep . Furthermore, since only an organization can request GUIDs for a user, this really feels like app-specific functionality.

**Comment by robvanmieghem** [comment]
I like this feature,  since we want to move away from username as much as possible, it would be like a consumer specific ID and since you can request multiple, this prevents datamining on them

**Comment by LeeSmet** [comment]
@robvanmieghem @despiegk See https://github.com/itsyouonline/identityserver/blob/1.0.0/specs/GUID_feature.md for a small spec + some remarks about this feature. Please approve , post remarks, give feedback, etc...

**Comment by robvanmieghem** [comment]
@LeeSmet  shouldn't we allow these identifiers to be used instead of {username} in the api?

**Comment by LeeSmet** [comment]
yes, that is the plan, however that brings up [a first possible implementation issue](https://github.com/itsyouonline/identityserver/blob/1.0.0/specs/GUID_feature.md#possbile-issues)

**Comment by LeeSmet** [comment]
Updated the spec to be more clear / add another possible issue

**Comment by robvanmieghem** [comment]
@LeeSmet where are the usernames used in json structures?

**Comment by LeeSmet** [comment]
A few places in the organizations api currently, for example when inviting a user (in this case the json is just a string with a username/email/phone number). Also when chaning the role of a user in an organization (promoting member to owner or the other way around), in this case the json body is a username and a (new) role

**Comment by LeeSmet** [comment]
Ability to create, list and lookup such ids implemented according to the spec written earlier, bar some small changes to solve some practical issues. I'll update the spec later.

Still need to implement the ability to use these as valid identifiers in urls and request bodies
