### ISSUE TITLE
Investigate database sharding solution

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#589]
Need to investigate the exact requirements on the backend, risks, infrastructure requirements, ...

**Comment by LeeSmet** [comment]
Markdown documents about specs and related things collected in the specs folder on the 1.0.0 branch: https://github.com/itsyouonline/identityserver/tree/1.0.0/specs/database_sharding

**Comment by LeeSmet** [comment]
Due to the necessity of a shard key index, some unique indexes will need to be dropped. We need to investigate how we can ensure uniqueness without leaving potential race conditions

**Comment by despiegk** [comment]
no need to do this, will go to blockchain solution
