### ISSUE TITLE
Show helpfull error message if not all scopes are provided in an oauth flow

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#600]
When doing an oauth flow, the user must authorize al requested scopes. Currently there still is the option to provide a `None` scope. Also if not all scopes can be provided or the user gives a `None` scope and clicks authorize, they get stuck in an endles loop without error message

**Comment by LeeSmet** [comment]
Right now all scopes requested must be provided. However the UI allows us to proceed even if this is not the case. The backend then redirects to the authorize screen again. As a result, the end users experiences what looks like a page refresh when clicking the authorize button and not providing all the requested scopes.

According to the documentation of IYO, the user can choose what info he shares (if any). Also there is the option to select "None" in the authorization, indicating the user does not want to share something. 

So we should also consider if we want to allow users to omit certain info that they can't or don't want to provide. This might then break some existing implementations that rely on all info requested being given if the callback to the 3rd party is made. Or we keep the current functionality, in which case we should at the very least strip out the `None` values. In case of the latter, it might be best to do a proper rework of the flow on the backend: instead of creating an incomplete authorization and then redirecting back to the authorization screen when checking this in the next step, the authorization handler can then detect missing requested scopes, and simply return a json response. This would make it easy to implement some nice error messages in the UI, e.g.: You must share at least one email address with this application to be able to continue. This would be better than the current `infinite loop` approach imo.

**Comment by nbabenko** [comment]
Still have an issue related with error messages:
https://docs.greenitglobe.com/ThreeFold/proj_onboarding_tools/issues/25

**Comment by LeeSmet** [comment]
For now, we will make all requested properties (except organizations) required. In the future, an optional scope concept can be implemented.
