### ISSUE TITLE
Send email when iyo user gets a notification on iyo

### ISSUE THREAD

**Issue by andhartl** [itsyouonline/identityserver#605]
user should get an email once a notification is waiting for him in iyo

**Comment by robvanmieghem** [comment]
what is the notification channel? phonenumber /email?

**Comment by LeeSmet** [comment]
Some considerations:
- There is no concept of a `notification` in the db, this is just a method which looks for some predefined fields such as invitations.
- An email is already sent if a user is invited to an org based on his email address. The same applies for sms/phone number. Perhaps we should expand this system to always send an email if an invite is sent to a known user and he has a validated email address

**Comment by LeeSmet** [comment]
The approach here is probably to always send an email once an invite is created
