### ISSUE TITLE
If someone is a member from an org, he/she can be added to suborgs without acceptance

### ISSUE THREAD

**Issue by Virgil3** [itsyouonline/identityserver#619]
Right now if an admin wants to move a IYO member to a suborg they get a notification that they need to accept. This system is cumbersome and causing confusion for our users.

What we want is a system that doesn't wait for acceptance from the user. If someone is already a member of an org then the user can be added to any suborg by admins. They will just get a notification that they have been added to the suborg.

The same goes for removing people from suborgs.

**Comment by Virgil3** [comment]
Apparently moved to https://github.com/itsyouonline/identityserver/issues/621

**Comment by despiegk** [comment]
is this now for all organizations?
