### ISSUE TITLE
I can't accept an invitation with a new user

### ISSUE THREAD

**Issue by islamTaha12** [itsyouonline/identityserver#626]
**Description**
I have two accounts one was created 3 months ago and a new one just created this week. I send an invitation for those accounts. I checked from the portal of those two accounts and made sure that they received the invitation. I tried to use the iyo's client to accept this invitation. For the same code, I can accept for the old account and I cant for the new account. 

**Expected result**
New users should be able to accept invitations.

**Comment by ahmedelsayed-93** [comment]
organization testcases 
https://github.com/itsyouonline/testing/blob/master/api_testing/testsuite/b_extended/test02_organizations.py

**Comment by LeeSmet** [comment]
After investigation, it seems like this was fixed in a1e8c970535f3d7ad49306211205d2fa442c8dd5

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
