### ISSUE TITLE
Unable to login to site that uses IYO oauth2 flow

### ISSUE THREAD

**Issue by grimpy** [itsyouonline/identityserver#628]
When the browser opens the page to approve the requested scopes clicking the authorize button yields the following in the browser console, and nothing happens from the user point of view.

Note: This appears to only happen with firefox, it seems to work with chrome

```
Error: event is not defined
confirm/<@https://itsyou.online/components/user/authorizeController.js:357:21
processQueue@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:16606:28
scheduleProcessQueue/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:16622:27
$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:17913:16
$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:17727:15
$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:18021:13
ngEventHandler/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:26495:17
defaultHandlerWrapper@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:3540:3
eventHandler@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:3528:9
 angular.js:14110:18
```
![170928_114540](https://user-images.githubusercontent.com/143869/30960746-3bc4010a-a444-11e7-866a-ba81dc2c9079.png)

**Comment by LeeSmet** [comment]
Weird that it works in chrome. Issue is that the `event` var is not propagated when I added a layer in between to check the verified email addresses and phone numbers

**Comment by LeeSmet** [comment]
Also only occurs if a memberof scope is requested it seems

**Comment by LeeSmet** [comment]
Deployed in production
