### ISSUE TITLE
Removing an organization invite removes wrong invite from UI

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#630]
Update all instances of `track by $index` in this file https://github.com/itsyouonline/identityserver/blob/5bcb57ee2096ebbdb29f7a7f04347fe4d3542c91/siteservice/website/components/organization/views/detailTabsPeople.html

to something that's unique, e.g. combination of invite.user and invite.role.

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
