### ISSUE TITLE
Return info about the organizations if there is a valid authorization in the userinfo api endpoint

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#631]
Currently the userinfo endpoint does not return info about the organizations despite the raml saying that it does. In order to generate the clients correctly, I removed the Organization[] item in the raml. See c82b381ccdbc22cc4bed22af2d5b60b720cea8d2. Even if a user:admin token is supplied, the organizations list remains unused. The problem is that since there is no initialization, the json returns None for this property, which caused errors in the generated client. Should the organizations value be added again, while loading all the organizations a user has access to (potentially filtering this to only those authorized by user:memberof scopes if the authorization does not have user:admin access), or just forget about this entirely?

**Comment by ahmedelsayed-93** [comment]
found an issue 
api ```GET /users/<username>/organizations``` with scope ```user:memberof:<org>``` returns 403 instead of filtering the organizations to only those authorized by user:memberof scopes

**Comment by LeeSmet** [comment]
Related to #703
