### ISSUE TITLE
Jwt endpoint ingores validity param when called with existing parent JWT

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#632]

**Comment by LeeSmet** [comment]
Steps to reproduce:
1. Create a jwt
2. Make a call to the JWT endpoint (/v1/oauth/jwt), with a `validity=xxx` queryparameter, and the jwt from step 1 as the authentication
3. The new JWT should have an expiration time which matches the custom validity period specified in step 2

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-117-g2b2fb7a
