### ISSUE TITLE
Spaces not allowed when inputting phone number

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#64]
Maybe allow spaces when inputting phone number:

![screen shot 2016-05-23 at 16 11 52](https://cloud.githubusercontent.com/assets/13795109/15474676/2ab2fca8-2106-11e6-9b2d-98aaca1452bb.png)

**Comment by robvanmieghem** [comment]
We might allow this for input but store it without regardless

**Comment by lucasvanhalst** [comment]
fixed in #124
