### ISSUE TITLE
Separate email validation and phone validation in registration flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [itsyouonline/identityserver#640]
If someone presses login without validating their email address first, then the login button does nothing. We should point out to the user that they must not forget to validate his email address first. 

![image](https://user-images.githubusercontent.com/17762105/31124532-2098e756-a845-11e7-9a79-b2ba7e0e25c0.png)

**Comment by LeeSmet** [comment]
Replace Tab Titles with Step 1: ..., Step 2: ...

Also split validation into 2 screens: Validate SMS -> Validate Email

**Comment by LeeSmet** [comment]
example design for Mobile

![photo_2017-10-05_16-26-09](https://user-images.githubusercontent.com/22023708/31232404-12047f92-a9ea-11e7-8517-791c14691016.jpg)
![photo_2017-10-05_16-26-14](https://user-images.githubusercontent.com/22023708/31232405-120820f2-a9ea-11e7-9983-cdc56598bc0c.jpg)
![photo_2017-10-05_16-26-21](https://user-images.githubusercontent.com/22023708/31232406-1218461c-a9ea-11e7-9951-54fd03ce3332.jpg)
