### ISSUE TITLE
Next button looked still disabled after phone validation code was entered

### ISSUE THREAD

**Issue by bart-at-mobicage** [itsyouonline/identityserver#644]
The button looked like it was still disabled. I could click it though.

<img width="432" alt="screen shot 2017-10-07 at 17 37 28" src="https://user-images.githubusercontent.com/17762105/31309434-5c2cfe30-ab86-11e7-8083-9b0fa584954a.png">

**Comment by LeeSmet** [comment]
browser version && steps to reproduce?

**Comment by bart-at-mobicage** [comment]
Happened on iPhone 5S simulator with iOS 8.1 while going through the registration flow.

**Comment by LeeSmet** [comment]
It seems that the correct css classes are indeed applied to the button, but the render engine in safari 8.x sometimes does not pick up the changes. Triggering a UI update by pressing any button causes the next button to be rendered correctly (no longer looks disabled). We might need to check if we can manually run a digest, or implement a fake button and a click handler that is triggered after a short timeout to force a UI refresh
