### ISSUE TITLE
Use Itsyou.online instead of "it's you online" when adding GitHub

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#65]
Change "it's you online" to "Itsyou.online" in authorization screen

![screen shot 2016-05-23 at 16 52 37](https://cloud.githubusercontent.com/assets/13795109/15474819/e521c290-2106-11e6-9402-9b0b40a6a7a2.png)

**Comment by lucasvanhalst** [comment]
I think @robvanmieghem should create an application as the itsyou.online github organization instead of using the one I used for testing

**Comment by robvanmieghem** [comment]
@lucasvanhalst The github and facebook links are hardcoded in the javascript:
https://github.com/itsyouonline/identityserver/blob/master/siteservice/website/components/user/controller.js#L457

So the settings in the server do not matter
