### ISSUE TITLE
List sites/applications "linked" to itsyou.online

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#67]
I've been signing in at http://dev.whmcs.greenitglobe.com:7180/whmcs with Itsyou.online

I'd like to see that listed somewhere at Itsyou.online and in a later stage also see which information I've been sharing with that whmcs site

**Comment by robvanmieghem** [comment]
This is where the authorization tab is for.

**Comment by yveskerwyn** [comment]
https://github.com/gig-projects/org_development/issues/189
