### ISSUE TITLE
Make address add button render errros and focus invalid input field

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#671]
0e3dfeb786c4d4f393f5584bf2835fd173ff9dad Disabled the add button in case of invalid fields. it might however not be clear for some users that this is caused by not all required fields being filled in. To alleviate this, the add button should be clickable, rendering errors on all invalid inputs, and focusing the first invalid input. The first point has already been addressed in the linked commit, the main problem is that focusing seems to be pretty hard for angular

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
