### ISSUE TITLE
Block already known phone numbers and email addresses everywhere

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#672]
## Current situation:

Because some users created duplicate accounts, #649 was implemented as a temporary fix by preventing the reuse of telco nrs, and email addresses. Obviously this is not an ideal solution, and is a bug in itself, for at least the aforementioned reason. This means a user can only create a duplicate account if he has more than 1 phone number (the same applies for email addresses, but creating an email address is both free and easy. Also the same email address can be reused by e.g. changing `firstname@provider` to `firstname+1@provider`). Note that it was decided to only block new duplicate accounts this way, and not remove existing ones.

## Issue's being raised

As said, it was decided to not remove the already existing duplicate accounts. This causes some people to raise the following points, which they consider to be an issue:
1. It is still possible to log into accounts with the username (one that was chosen when this was still possible, or the generated one if they know/guess this).
2. It is possible to log in to 2 separate accounts if I used 2 emails: the email address can be used to log in to the account without the phone number (note that 2 emails are not strictly necessary, one account could hold the phone number. the other the email address), even if the usernames are not known.
3. We only block adding already confirmed phone numbers and email addresses in the registration flow. As a result, if a person manages to log in to 2 accounts, he can move validated phone numbers and email addresses from one account to the other.
4. Duplicate accounts must not be possible, and so a script should be written to automatically merge all duplicate accounts (or we do this manually).

## Remarks on the previously raised points/issues

1. Possible to log in using username: This does not feel like an issue, more like a feature. A lot of early users have created their account and explicitly chose a username. If we now remove the ability to log in using the username, this could cause confusion. Also, this does not matter for new users who can only created 1 account anyway.
2. While this is indeed true, this required that the user already had 2 accounts in this setup. Furthermore, moving a piece of information between 2 accounts does not break anything (3rd parties must be able to handle information disappearing. The user might also just have removed it). It is also possible that a user with an existing account get a new telephone number, which turns out to be already known (as it belonged to another user but he moved to another country, for example).
3. See 2
4. Even if this is done without losing info on our side (thus requiring major effort on our part), it is possible that this causes issues with 3rd party integrations since these usually bind to the username at this time. 

The main reason for the above is to ensure that accounts map 1 to 1 to physical users. Although this would be ideal, currently this is not possible imo: a user can just get another phone number, create a new email address, and fill in whatever he likes as his name. This leaves us with 2 disjoint sets of information ( both with a confirmed phone number and email address), but both controlled by a single user.

**Comment by despiegk** [comment]
it was decided to not remove the already existing duplicate accounts: THIS IS MISTAKE FIX ASAP

**Comment by LeeSmet** [comment]
Cleanup of duplicate accounts has been executed
