### ISSUE TITLE
ownership inheritance on list user organizations is incorrect

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#674]
After the introduction of 5e5ff182b9e4bc357109d1d6724c92975579aa07, some of the suborganizations where one should be an owner are not correctly reflected in the user organization list. While the user is an owner in the top lvl org, he is only a member in some suborgs

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
