### ISSUE TITLE
regenerate client using up-to-date go-raml

### ISSUE THREAD

**Issue by GlenDC** [itsyouonline/identityserver#675]
The generated clients haven't been updated in a while. However, in the meanwhile, go-raml received quite some improvements/fixes/updated.

The current client seems to try to parse success bodies even though a non-success code has been received (e.g. `409`). An example of this was encountered in the client command-line tool of github.com/zero-os/0-stor:

```
$ zerostorcli --conf /gopath/src/github.com/zero-os/0-stor/client/cmd/zerostorcli/config.yaml namespace set-acl --namespace xtremx_881 --userid ah-elsayed -w
```

> give member permission failed: code=409, err=invalid character 'C' looking for beginning of value

As you can see it is trying to parse the success body of an error response body (`"Conflict"`).

@zaibon told us that bugs like this have been fixed in the latest go-raml, so can we please regenerate the IYO clients?

**Comment by LeeSmet** [comment]
Indeed, I was planning to do this after the discussed changed where added to go-raml. Guess I forgot :)

Either way, the new golang clients have been added on their respective branches. See `master` branch for the version reflecting the API currently in production, atm this is version `0.9.16.1`. See the `1.0.0` branch for the API from the development branch. They should both be similar for the moment.

Go-raml commit: https://github.com/Jumpscale/go-raml/commit/4097e3b96fe896f16111526241ca0ca22ceaf152
Go-raml version (git describe): raml1.0-rc1-553-g4097e3b
Commit for client on master branch: 0bef5af0c677792b39d45ae66f2043f197e215de
Commit for client on 1.0.0 branch: f081c7b7bc71df10b74bda38e1602b7c7623491c
