### ISSUE TITLE
client.api.AcceptMembership returns 404 or 403

### ISSUE THREAD

**Issue by islamTaha12** [itsyouonline/identityserver#676]
I sent an invitation to dina_magdy, she received it, then I tried to accept the invitation using the API client
```python
ipdb>self.iyo_slave_client.api.AcceptMembership(namespace_value, 'member', 'magdyd@greenitglobe.com').status_code
403
ipdb> self.iyo_slave_client.api.AcceptMembership(namespace_value, 'member', 'dina_magdy').status_code
404
```

here is the invitation mail:
![image](https://user-images.githubusercontent.com/17981089/33277135-4b1981f8-d3a0-11e7-846e-0c69424212b6.png)

and I can GetUser using this api which means that the api client is configured fine.

**Comment by LeeSmet** [comment]
First of all, this is not the plain IYO client. Please provide the actual call to IYO (with the IYO generated client, or an HTTP call this client creates itself), with all the values that are being passed to it. Untill then, I can't investigate if this is an actual bug on IYO or on your side

Second, the currently deployed IYO version only sends an email in case the email address you invite is not yet validated by anyone. This strongly suggests that some additional account configuration needs to be done (i.e. make sure the email address is validated), or that you made a typo, etc... This invite can be accepted by clicking the button in the email, then logging in with the desired account. This account will accept the invitation and the email address will be confirmed for this account.

**Comment by LeeSmet** [comment]
@islamTaha12

**Comment by LeeSmet** [comment]
Closing due to lack of response
