### ISSUE TITLE
Create suborganization doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#68]
See screenshots:

![screen shot 2016-05-24 at 17 41 08](https://cloud.githubusercontent.com/assets/13795109/15510257/faf00188-21d6-11e6-9ddc-0bb0f4d7f471.png)

![screen shot 2016-05-24 at 17 41 16](https://cloud.githubusercontent.com/assets/13795109/15510258/fe98d576-21d6-11e6-8d4d-9b7d685355a8.png)

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/commit/147cfdd0206e9d207bc0720fb30292884c5e9959
