### ISSUE TITLE
How to remove shared information with org using API

### ISSUE THREAD

**Issue by rajanmayekar** [itsyouonline/identityserver#681]
Hi,

I am using oauth authentication to access the itsyou user's information with itsyou org.
If I logged in to user's account, I can see that from https://itsyou.online/#/authorizations.
So remove the shared information with org using API, I am assuming I should use API
DELETE /users/{username}/authorizations/{grantedTo}?access_token=<user's oauth access token>
But it give forbidden. Please let me know if this is an issue or I am missing something.

**Comment by LeeSmet** [comment]
Hi,

Deleting an authorization can currently not be done with the access token. The authorization list is used as a way to check if an access token is still valid, but can also be used as a reminder for users to check which info they shared to what organization. Therefore this api endpoint can only be invoked by the user himself. Should your organization no longer wish to access the user's information, it suffices to delete the user's access token on the organization. The only way to get a new access token then is for the user to explicitly log in again to your organization
