### ISSUE TITLE
UNFRIENDLY ERROR when logging in with user that have no access

### ISSUE THREAD

**Issue by nbabenko** [itsyouonline/identityserver#683]
1. Create a new IYO user.
2. Try to login with it to crm.threefoldtoken.com
3. Expected result: Error message "Sorry, you have no access level to open this resource"
4. Actual result: 
"This site can’t be reached
The webpage at https://crm.threefoldtoken.com/iyo_callback?code=jzkSdEnccAy2hJJaPJ6_hyDth7Wt&state=%2F#/authorize?client_id=threefold.crm_users&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http:%2F%2Fcrm.threefoldtoken.com:80%2Fiyo_callback&response_type=code&scope=user:address,user:email,user:phone&state=%2F might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED"

**Comment by LeeSmet** [comment]
How insufficient access is handled is up to the third party application, not IYO. Also, it seems that this is a generic browser error message generated because the target could not be reached, so not IYO related
