### ISSUE TITLE
ismember checks take too much resources

### ISSUE THREAD

**Issue by LeeSmet** [itsyouonline/identityserver#687]
The calls to the `ismember` api endpoint do a lot of database calls. This causes spamming of this endpoint to effectively turn into a dos attack (the bottleneck being the mongo slowing down), and results in overal performance degradation.

A possible solution is to create a separate collection, where the exact access for users is cached:
every organization has an entry here with a list of people who have owner access and a list of people who have member access. This would mean that the `ismember` api endpoint results in only a single query. As a downside, this means that every time someone is added or removed from an organization, or a suborganization is created, or an organization is added to another organization... a significant part of this collection will need to be recalculated, which might be an issue in its own right

**Comment by lucasvanhalst** [comment]
related to #638

**Comment by LeeSmet** [comment]
Reused the improved code from issue #638. Will need to gather some info about the performance with this to check if extra measures are needed
