### ISSUE TITLE
Getting Permissions for invited users

### ISSUE THREAD

**Issue by elafont** [itsyouonline/identityserver#689]
* I have 2 users, one is owner of a test260.0stor and it does create a namespace (using the zstor tool)
```
$ bin/zstor namespace create  t260
INFO[0000] namespace "t260" created 
```

* Then the owner invites another user, not related to organization test260, or any other, to become part of the namespace t260, doing this from IYO web site

* From that moment, User2 has permissions on t260 even when he has not accepted the invitation, although is not a big deal, he just got admin rights
```
$ bin/zstor namespace permission get User2  t260  
Read: false
Write: false
Delete: false
Admin: true
```
* The permissions won't change after User2 accepts the invitation.
* User2 **can not** ask for his permissions, as always he receive a 
```
 $ bin/zstor namespace permission get User2 t260 -C c2.yaml
Error: failed to retrieve permission for User2:t260: Failed to retrieve user permission :
```
Digging in the code, I've observed that the error returned from the GetPermission->GetInvitations functions is 403, with an empty body and no other explanations. Trying the call manually triggers a security warning.

The file c2.yaml contains the app-id and app-secret for the User2
* zstor anyways can do other operations like uploading a file to a 0-stor storage as User2
```
$ bin/zstor file upload aFile  -C c2.yaml -n t260
INFO[0000] Setting namespace config to [t260]           
INFO[0000] data from "aFile" uploaded as key = "aFile"
```

**Comment by elafont** [comment]
I'm working now on a test sample, that would make it simple to verify

**Comment by lafont-e** [comment]
This is a very similar case to the one in #690 

I have 2 users on ityouonline, User1 (lafonte@greenitglobe.com) is the owner of the organization test260

test260 has suborganizations 0stor (this comes from a problem raised on 0-stor and another subdomain named t260 

User2 (miguel.aguila@me.com) was invited to be a member of test260.0stor.t260. User2 accepted the invitation but I'm not able to retrieve the permissions of User2 while login as User2.

I created a small application to illustrate  the case 
```go
// test code for  itsyouonline issue 689: Permission problems

package main

import (
	"fmt"
	"github.com/itsyouonline/identityserver/clients/go/itsyouonline"
	"log"
	"net/http"
	"os"
)

const ( // Yes, those are real API keys, Will change them, but left here so it's easier to make the test
	user1        = "lafonte@greenitglobe.com"
	user1Id      = "otzMc8WXFwBqdfU_YiPiMQBgTkeU"
	user1Secret  = "S_ZiZNGWZOe_7ZzkTdbkmCV_ZiZp"
	organization = "test260"
	user2        = "miguel.aguila@me.com"
	user2Id      = "UH9WSWpo9aKqPtNWvWV9PPJpt-vB"
	user2Secret  = "Oan_qTZl-9nGstgwEXuQelSE2y1K"
)

type config struct {
	Organization      string
	ApplicationID     string
	ApplicationSecret string
}
type permissions struct {
	read, write, delete, admin bool
}

var (
	iyo1Cfg = config{
		Organization:      organization,
		ApplicationID:     user1Id,
		ApplicationSecret: user1Secret}
	iyo2Cfg = config{
		Organization:      organization,
		ApplicationID:     user2Id,
		ApplicationSecret: user2Secret}
)

func usage() {
	log.Fatalf("Usage: %s [owner|guest] <namespace> <user>", os.Args[0])
}

func main() {
	if len(os.Args) < 3 {
		usage()
	}

	requester := iyo1Cfg
	if os.Args[1] == "guest" {
		requester = iyo2Cfg
	}
	ns := os.Args[2] // 2nd parameter is namespace to operate
	user := os.Args[3]

	iyo1Clnt := itsyouonline.NewItsyouonline()

	perm, err := getPermissions(iyo1Clnt, &requester, ns, user)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Read ", perm.read)
		fmt.Println("Write ", perm.write)
		fmt.Println("Delete ", perm.delete)
		fmt.Println("Admin ", perm.admin)
	}
}

// getPermission retrieves the permission a user has for a namespace
// returns true for a right when user is member or invited to the namespace
func getPermissions(iyoClnt *itsyouonline.Itsyouonline, iyoCfg *config, ns, userID string) (permissions, error) {
	perm := permissions{}
	org := iyoCfg.Organization + ".0stor." + ns

	_, _, _, err := iyoClnt.LoginWithClientCredentials(iyoCfg.ApplicationID, iyoCfg.ApplicationSecret)
	if err != nil {
		return perm, fmt.Errorf("[Error] getPermissions: Login failed:%v", err)
	}

	if perm.read, err = permission(iyoClnt, org, "read", userID); err == nil {
		if perm.write, err = permission(iyoClnt, org, "write", userID); err == nil {
			if perm.delete, err = permission(iyoClnt, org, "delete", userID); err == nil {
				perm.admin, err = permission(iyoClnt, org, "admin", userID)
			}
		}
	}

	if err != nil {
		return perm, err
	}

	return perm, nil
}

func permission(iyoClnt *itsyouonline.Itsyouonline, org, perm, userID string) (bool, error) {
	right := org // admin right uses the full org name
	if perm != "admin" {
		right += "." + perm
	}

	fmt.Println("Asking for permission ", right)
	invitations, resp, err := iyoClnt.Organizations.GetInvitations(org, nil, nil)
	if err != nil || resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("[Error] permission: unable retrieve invitations Status:%+v Err:%+v", resp.Status, err)
	}

	members, resp, err := iyoClnt.Organizations.GetOrganizationUsers(org, nil, nil)
	if err != nil || resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("[Error] permission: unable retrieve membership Status:%+v Err:%+v", resp.Status, err)
	}

	return (isMember(userID, members.Users) || isInvited(userID, invitations)), nil

}

func isMember(target string, list []itsyouonline.OrganizationUser) bool {
	for _, v := range list {
		if target == v.Username {
			return true
		}
	}
	return false
}

func isInvited(target string, invitations []itsyouonline.JoinOrganizationInvitation) bool {
	for _, invite := range invitations {
		if target == invite.User || target == invite.Emailaddress {
			return true
		}
	}
	return false
}
```

Same as before a **go build -o getperms** should create a small executable

The application has 2 requesters owner and guest, when selecting owner, the login will be done with the keys of the owner of the test260.0stor.t260 organization, when guest is selected, the keys of the invited user will be used instead.

So we want to know the permissions for the guest user, this time login as the owner
```
$ ./getperms  owner  t260 miguel.aguila@me.com
Asking for permission  test260.0stor.t260.read
Asking for permission  test260.0stor.t260.write
Asking for permission  test260.0stor.t260.delete
Asking for permission  test260.0stor.t260
Read  true
Write  true
Delete  true
Admin  true
```
Seems right..., but when trying to retrieve the permissions login as the guest ...
```
$ ./getperms  guest  t260 miguel.aguila@me.com
Asking for permission  test260.0stor.t260.read
[Error] permission: unable retrieve invitations Status:403 Forbidden Err:
```
It does not respond with what I expected, as a 403 was not expected, the guest has permissions on the suborganization and has accepted the invitation and .... it should work, or at least that is what I think.

As before (690), this can be an error on the IYO libraries or on the sample code shown here, but is beyond my knowledge, would be very grateful if you could provide some insight on the problem.

**Comment by LeeSmet** [comment]
>User2 (miguel.aguila@me.com) was invited to be a member of test260.0stor.t260. User2 accepted the >invitation but I'm not able to retrieve the permissions of User2 while login as User2.

The problem is that the second user is indeed a member of the organization. As described in the api docs, the `GetInvitations` call requires organization owner privileges. So the server rightfully returns `403 Forbidden`

![screenshot from 2018-01-17 10-17-37](https://user-images.githubusercontent.com/22023708/35034813-b0b74e90-fb6f-11e7-8982-1ca788866313.png)
