### ISSUE TITLE
DELETE requests in generated go client perform a GET instead

### ISSUE THREAD

**Issue by elafont** [itsyouonline/identityserver#690]
* I have a User1 who is the owner of test260.0stor organization (all tests done with zstor)
* I create a new namespace eraseme
```
$ zstor namespace create eraseme  
INFO[0000] namespace "eraseme" created        
```
* User1 has all the rights on eraseme
```
$ zstor namespace permission get User1  eraseme
Read: true
Write: true
Delete: true
Admin: true
```
* When trying to delete the namespace eraseme, or any other created 
```
$ zstor namespace delete  eraseme  
INFO[0000] namespace "eraseme" deleted 
```

* All seems right, but going to the IYO Web site shows that *eraseme* is still live and working 
```
$ zstor file upload aFile  -n eraseme 
INFO[0000] Setting namespace config to [eraseme]        
INFO[0000] data from "aFile" uploaded as key = "aFile"
```

No matter how many times I ask for a delete, the namespace is never erased.

**Comment by elafont** [comment]
I'm working now on a test sample, that would make it simpler to verify the issue

**Comment by robvanmieghem** [comment]
iyo does not know anything about namespaces so the issue you created should be in 0-stor and can refer to an iyo issue but with an iyo problem and in iyo terminology.

**Comment by lafont-e** [comment]
I have a user (lafonte@itsyouonline.com) which is the owner of the organization test260 

test260 has a suborganization 0stor (this comes from a problem in 0-stor) and various additional 
suborganizations .
test.0stor.ns260, test.0stor.n260, test.0stor.n260b, test.0stor.n260c,test.0stor.t260, test.0stor.eraseme, test.0stor.kk, test.0stor.kk1, test.0stor.kk2, test.0stor.kk3, test.0stor.t260a, test.0stor.test260, test.0stor.test260b 

I try to delete some  of those suborganization, as they are samples without utility used just to do some tests,  but now I'm unable to do so, not from the web site, not from code using the IYO libraries 

I have created a small application to show the problem.
```go
// test code for  itsyouonline issue 690: deleting a namespace

package main

import (
	"fmt"
	"github.com/itsyouonline/identityserver/clients/go/itsyouonline"
	"log"
	"net/http"
	"os"
)

const (
	user1        = "lafonte@greenitglobe.com"
	user1Id      = "otzMc8WXFwBqdfU_YiPiMQBgTkeU"
	user1Secret  = "S_ZiZNGWZOe_7ZzkTdbkmCV_ZiZp"
	organization = "test260"
)

type config struct {
	Organization      string
	ApplicationID     string
	ApplicationSecret string
}

var (
	iyo1Cfg = config{
		Organization:      organization,
		ApplicationID:     user1Id,
		ApplicationSecret: user1Secret}
)

func usage() {
	log.Fatalf("Usage: %s [create|delete] <namespace> ", os.Args[0])
}

func createNs(iyoClnt *itsyouonline.Itsyouonline, ns string, iyoCfg *config) {
	fmt.Println("Creating namespace ", ns)

	_, _, _, err := iyoClnt.LoginWithClientCredentials(iyoCfg.ApplicationID, iyoCfg.ApplicationSecret)
	if err != nil {
		log.Fatalf("[Error] createNs: Login failed:%v", err)
	}

	// create Organization 0stor namespace
	namespaceID := iyoCfg.Organization + "." + "0stor"
	org := itsyouonline.Organization{Globalid: namespaceID}

	_, resp, err := iyoClnt.Organizations.CreateNewSubOrganization(iyoCfg.Organization, org, nil, nil)
	// Ignore StatusConfict(409) expected when 0stor suborganization already exists
	if err != nil && resp.StatusCode != http.StatusConflict { // Any other than 409 returns error
		log.Fatalf("[Error] createNs: Creating 0stor namespace code=%v, err=%v", resp.StatusCode, err)
	}

	// create 0stor suborganization
	org = itsyouonline.Organization{Globalid: namespaceID + "." + ns}
	_, resp, err = iyoClnt.Organizations.CreateNewSubOrganization(namespaceID, org, nil, nil)
	if err != nil {
		if resp.StatusCode == http.StatusConflict {
			log.Fatalf("[Error] createNs: namespace (%[2]s.%[1]s) already exists", ns, namespaceID)
		}
		log.Fatalf("[ERROR] createNs: Creating %s.%s namespace code=%v, err=%v", namespaceID, ns, resp.StatusCode, err)
	}

	// Assigning permissions
	namespaceID = namespaceID + "." + ns
	for _, perm := range []string{"read", "write", "delete"} {
		org := itsyouonline.Organization{Globalid: namespaceID + "." + perm}

		_, resp, err := iyoClnt.Organizations.CreateNewSubOrganization(namespaceID, org, nil, nil)
		if err != nil {
			log.Fatalf("[ERROR] createNs: Assigning permissions code=%v, err=%v", resp.StatusCode, err)
		}
	}

	fmt.Printf("namespace %q created\n", ns)
	fmt.Println()
}

func removeNs(iyoClnt *itsyouonline.Itsyouonline, ns string, iyoCfg *config) {
	org := iyoCfg.Organization + "." + "0stor" + "." + ns
	fmt.Println("Removing namespace ", org)

	_, _, _, err := iyoClnt.LoginWithClientCredentials(iyoCfg.ApplicationID, iyoCfg.ApplicationSecret)
	if err != nil {
		log.Fatalf("[Error] removeNs: Login failed:%v", err)
	}

	resp, err := iyoClnt.Organizations.DeleteOrganization(org, nil, nil)
	if err != nil {
		log.Fatalf(
			"[ERROR] removeNs: deleting namespace failed  code: %v err: %v", resp.Status, err)
	}

	fmt.Printf("namespace %q removed\n", ns)
	fmt.Println()
}

func main() {
	if len(os.Args) < 3 {
		usage()
	}

	// iyoCl, err := iyo.NewClient(iyo1Cfg) // 0-Stor client
	iyoCl := itsyouonline.NewItsyouonline()

	ns := os.Args[2] // 2nd parameter is namespace to operate

	switch os.Args[1] {
	case "create":
		fmt.Print("1st Try.... ")
		createNs(iyoCl, ns, &iyo1Cfg)
		fmt.Print("2nd Try (Should fail) .... ")
		createNs(iyoCl, ns, &iyo1Cfg)
	case "delete":
		fmt.Print("1st Try.... ")
		removeNs(iyoCl, ns, &iyo1Cfg)
		fmt.Print("2nd Try (Should fail) .... ")
		removeNs(iyoCl, ns, &iyo1Cfg)
	default:
		usage()
	}
}
```

Just **go build -o deltest** and it should create the executable *deltest*

We test creating a suborganization, it works, the 1st try creates the suborganization and repeating the operation complains about an existent suborganization (just what is expected)
```
$ ./deltest create kk5
1st Try.... Creating namespace  kk5
namespace "kk5" created

2nd Try (Should fail) .... Creating namespace  kk5
2018/01/16 14:43:37 [Error] createNs: namespace (test260.0stor.kk5) already exist
```

Then we proceed to delete the suborganization newly created, both times it says success, in fact we can repeat the command that always returns success
```
$ ./deltest delete  kk5
1st Try.... Removing namespace  kk5
namespace "kk5" removed

2nd Try (Should fail) .... Removing namespace  kk5
namespace "kk5" removed

$ ./deltest delete  kk5
1st Try.... Removing namespace  kk5
namespace "kk5" removed

2nd Try (Should fail) .... Removing namespace  kk5
namespace "kk5" removed
```

When you go the web site, you can check that test260.0stor.kk5 is still alive 

This can be a failure on the test code, or a failure on the IYO libraries, I did call DeleteOrganization(), if it's my code the one that fails would love some enlightenment, or it's something that belong to the internal libraries of itsyouonline. As my code comes mostly from 0-stor client libraries, if the error is the code we must solve the issue elsewhere or if it's not then it must be solved here.

**Comment by LeeSmet** [comment]
@lafont-e FYI: since this seems to be a live api key you hardcoded into your example, you should probably remove it from your profile and generate a new one, as now anyone could impersonate your IYO identity

**Comment by lafont-e** [comment]
Will do so, but for the moment, you should be able to verify and repeat the test

**Comment by LeeSmet** [comment]
Relevant issue in go-raml https://github.com/Jumpscale/go-raml/issues/421

**Comment by LeeSmet** [comment]
Clients have been regenerated with the latest version of go-raml, which  resolves this issue

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-117-g2b2fb7a
