### ISSUE TITLE
user shouldn't be able to remove the last verified email address or phone number

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#696]
### Scenario 
- Register new account or sign in to your account 
> Note: you won't be able to access this account again.
- Remove all verified email address.
- Remove all verified phone numbers.

### Expected behavior 
- User shouldn't be able to remove the last verified email address or phone number

### current behavior
- Verified emails and phone numbers will be deleted.
- If you signed out without adding new email or phone number and verify them, you won't be able to access this account again (*invalid credential error*)

### version
staging server
```{"Version":"v0.9.16-114-gdb03c0e"}```

**Comment by LeeSmet** [comment]
We should enforce that uses keep at least 1 verified email address (and possibly 1 verified phone, though this might not be needed if the autenticator app is configured)

**Comment by ahmedelsayed-93** [comment]
the error message is confusing 
![image](https://user-images.githubusercontent.com/24386820/35851872-f27b1d4e-0b31-11e8-8e98-57267af01354.png)
as the user shouldn't be able to remove the last verified phone number even if the 2FA is configured 

and the Cancel button lable is empty 
![image](https://user-images.githubusercontent.com/24386820/35851925-1c032094-0b32-11e8-9788-b2001844c1d9.png)
