### ISSUE TITLE
shouldn't be able to invite someone with non-existing email address

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#699]
try to invite someone using a fake email address 

![image](https://user-images.githubusercontent.com/24386820/35611590-343754a0-066e-11e8-8df7-ec1cf5604c8d.png)

### expected behavior 
 no user found matching this email address

**Comment by LeeSmet** [comment]
This is a feature. the email address is not known, and as such we will have sent it an email to invite said person to ItsYou.Online. If he follows the link, an account can be created which will then be added to this organization
