### ISSUE TITLE
v1/oauth/access_token api returns wrong scopes 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#701]
i sent the api request with scope ```user:memberof:<org>```
but in the response the scope field was ```user:admin```

![image](https://user-images.githubusercontent.com/24386820/35621074-c627c18e-068b-11e8-819c-0e77f2505f87.png)

**Comment by LeeSmet** [comment]
@ahmedelsayed-93  Are you a member of org-1?

**Comment by ahmedelsayed-93** [comment]
owner of it

**Comment by LeeSmet** [comment]
Seems like this only affects access tokens, if the additional `response_type=id_token` is also provided, it works as expected

**Comment by LeeSmet** [comment]
Not actually a bug. The access token is meant to act as a way of authenticating the client when doing calls to IYO, and must not be passed around. Should a client wish to give a third party access to (a subset of ) his information, a JWT must be used. JWT's do support this feature. In the future, there might be support for the creation of non admin api keys, which in turn could create acess tokens with limited scopes. But for now this is working as expected
