### ISSUE TITLE
members in organizations can remove, edit orgwners membership

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#704]
i'm a member of organization **environment** and i can remove, edit orgnwers role or include its members to be owner of organization **environment**

![image](https://user-images.githubusercontent.com/24386820/35776448-4ac1dd32-09a5-11e8-9242-b25b4ddabde4.png)

**Comment by LeeSmet** [comment]
UI bug, users are not actually able to change these settings if they are only members of the org

**Comment by ahmedelsayed-93** [comment]
issue still exists
![image](https://user-images.githubusercontent.com/24386820/35851787-b579c62a-0b31-11e8-8f9a-fe772652ec99.png)

**Comment by ahmedelsayed-93** [comment]
{"Version":"v0.9.16-122-g9e78e77"}
