### ISSUE TITLE
could not load api

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#82]
![image](https://cloud.githubusercontent.com/assets/6021844/15780309/22f95f8e-29b2-11e6-9557-65a5977cb579.png)

**Comment by despiegk** [comment]
also 2x same url;s

**Comment by robvanmieghem** [comment]
Originally the api console worked more or less fine using the features/new-raml branch of the api-console. After adding the oauth security schemes these resources are no longer available. This branch was abandoned by the api-console team in favour of the feature/raml-1.0 branch on which their development continued. In the mean time the raml spec progressed towards 1.0-rc2 which is incompatible with rc1 on a couple of places. The feature/raml-1.0 of api-console is merged in master by now but master is currently broken.
I expected/hoped that the api-console team would have solved the bugs by now.
This leaves us in a quite disastrous situation where the alternatives (like ramlo) are also still in development, missing functionality and still require quite some work from our side to integrate them.
Best option imo is to fix the blocking issues in api-console ourselves and try to get it merged upstream.
