### ISSUE TITLE
Allow creation of token from the UI

### ISSUE THREAD

**Issue by zaibon** [itsyouonline/identityserver#91]
I would be nice to let user create oauth token using the UI directly.
Now the only way to get oauth token is using the API and it requires to have a valid web server running to receive the token. In some situation you just want to have a token directly.

**Comment by robvanmieghem** [comment]
The concept of application keys has been added on a user level. Still need to validate if this is exposes everything through the UI to be acquire an oauth token.

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/blob/master/docs/oauth2/oauth2.md#user-api-key
